<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class BrandRenamesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('brand_renames')->delete();
        
        \DB::table('brand_renames')->insert(array (
            
            array (
                'id' => 1,
                'user_id' => 1,
                'name' => 'LADA',
                'bkey' => 'LADA',
                'rename_from' => 'RENAULT/LADA',
                'rename_from_bkey' => 'RENAULTLADA',
                'rename_to' => 'LADA',
                'rename_to_bkey' => 'LADA',
                'comment' => NULL,
            ),
            
            array (
                'id' => 2,
                'user_id' => 1,
                'name' => 'PEKAR',
                'bkey' => 'PEKAR',
                'rename_from' => 'ПЕКАР',
                'rename_from_bkey' => 'ПЕКАР',
                'rename_to' => 'PEKAR',
                'rename_to_bkey' => 'PEKAR',
                'comment' => NULL,
            ),
            
            array (
                'id' => 3,
                'user_id' => 1,
                'name' => 'AMC FILTERS',
                'bkey' => 'AMCFILTERS',
                'rename_from' => 'AMCFILTERS',
                'rename_from_bkey' => 'AMCFILTERS',
                'rename_to' => 'AMC FILTER',
                'rename_to_bkey' => 'AMCFILTER',
                'comment' => NULL,
            ),
            
            array (
                'id' => 4,
                'user_id' => 1,
                'name' => 'AUTOFREN',
                'bkey' => 'AUTOFREN',
                'rename_from' => 'AUTOFREN',
                'rename_from_bkey' => 'AUTOFREN',
                'rename_to' => 'AUTOFREN SEINSA',
                'rename_to_bkey' => 'AUTOFRENSEINSA',
                'comment' => NULL,
            ),
            
            array (
                'id' => 5,
                'user_id' => 1,
                'name' => 'AVA QUALITY COOLING',
                'bkey' => 'AVAQUALITYCOOLING',
                'rename_from' => 'AVA',
                'rename_from_bkey' => 'AVA',
                'rename_to' => 'AVA QUALITY COOLING',
                'rename_to_bkey' => 'AVAQUALITYCOOLING',
                'comment' => NULL,
            ),
            
            array (
                'id' => 6,
                'user_id' => 1,
                'name' => 'MALO',
                'bkey' => 'MALO',
                'rename_from' => 'ARCON',
                'rename_from_bkey' => 'ARCON',
                'rename_to' => 'MALO',
                'rename_to_bkey' => 'MALO',
                'comment' => NULL,
            ),
            
            array (
                'id' => 7,
                'user_id' => 1,
                'name' => 'AYWI PARTS',
                'bkey' => 'AYWIPARTS',
                'rename_from' => 'AYWI',
                'rename_from_bkey' => 'AYWI',
                'rename_to' => 'AYWI PARTS',
                'rename_to_bkey' => 'AYWIPARTS',
                'comment' => NULL,
            ),
            
            array (
                'id' => 8,
                'user_id' => 1,
                'name' => 'BEHR THERMOTRONIK',
                'bkey' => 'BEHRTHERMOTRONIK',
                'rename_from' => 'BEHR',
                'rename_from_bkey' => 'BEHR',
                'rename_to' => 'BEHR THERMOTRONIK',
                'rename_to_bkey' => 'BEHRTHERMOTRONIK',
                'comment' => NULL,
            ),
            
            array (
                'id' => 9,
                'user_id' => 1,
                'name' => 'BOSCH',
                'bkey' => 'BOSCH',
                'rename_from' => 'BOSCH UKГAD HAMULCOWY',
                'rename_from_bkey' => 'BOSCHUKГADHAMULCOWY',
                'rename_to' => 'BOSCH',
                'rename_to_bkey' => 'BOSCH',
                'comment' => NULL,
            ),
            
            array (
                'id' => 10,
                'user_id' => 1,
                'name' => 'BOSCH',
                'bkey' => 'BOSCH',
                'rename_from' => 'BOSCH ELEKTRONARZКDZIA',
                'rename_from_bkey' => 'BOSCHELEKTRONARZКDZIA',
                'rename_to' => 'BOSCH',
                'rename_to_bkey' => 'BOSCH',
                'comment' => NULL,
            ),
            
            array (
                'id' => 11,
                'user_id' => 1,
                'name' => 'BOSCH',
                'bkey' => 'BOSCH',
                'rename_from' => 'BOSCHFILTRY',
                'rename_from_bkey' => 'BOSCHFILTRY',
                'rename_to' => 'BOSCH',
                'rename_to_bkey' => 'BOSCH',
                'comment' => NULL,
            ),
            
            array (
                'id' => 12,
                'user_id' => 1,
                'name' => 'BOSCH',
                'bkey' => 'BOSCH',
                'rename_from' => 'BOSCHМWIECEPRZEWODY',
                'rename_from_bkey' => 'BOSCHМWIECEPRZEWODY',
                'rename_to' => 'BOSCH',
                'rename_to_bkey' => 'BOSCH',
                'comment' => NULL,
            ),
            
            array (
                'id' => 13,
                'user_id' => 1,
                'name' => 'BOSCH',
                'bkey' => 'BOSCH',
                'rename_from' => 'BOSCH PASKI',
                'rename_from_bkey' => 'BOSCHPASKI',
                'rename_to' => 'BOSCH',
                'rename_to_bkey' => 'BOSCH',
                'comment' => NULL,
            ),
            
            array (
                'id' => 14,
                'user_id' => 1,
                'name' => 'BOSCH',
                'bkey' => 'BOSCH',
                'rename_from' => 'BOSCH BAT',
                'rename_from_bkey' => 'BOSCHBAT',
                'rename_to' => 'BOSCH',
                'rename_to_bkey' => 'BOSCH',
                'comment' => NULL,
            ),
            
            array (
                'id' => 15,
                'user_id' => 1,
                'name' => 'BOSCH',
                'bkey' => 'BOSCH',
                'rename_from' => 'BOSCH WYCIERACZKI',
                'rename_from_bkey' => 'BOSCHWYCIERACZKI',
                'rename_to' => 'BOSCH',
                'rename_to_bkey' => 'BOSCH',
                'comment' => NULL,
            ),
            
            array (
                'id' => 16,
                'user_id' => 1,
                'name' => 'BOSCH',
                'bkey' => 'BOSCH',
                'rename_from' => 'BOSCH WTRYSK',
                'rename_from_bkey' => 'BOSCHWTRYSK',
                'rename_to' => 'BOSCH',
                'rename_to_bkey' => 'BOSCH',
                'comment' => NULL,
            ),
            
            array (
                'id' => 17,
                'user_id' => 1,
                'name' => 'CLEAN FILTERS',
                'bkey' => 'CLEANFILTERS',
                'rename_from' => 'CLEAN FILTER',
                'rename_from_bkey' => 'CLEANFILTER',
                'rename_to' => 'CLEAN FILTERS',
                'rename_to_bkey' => 'CLEANFILTERS',
                'comment' => NULL,
            ),
            
            array (
                'id' => 18,
                'user_id' => 1,
                'name' => 'LAUBER',
                'bkey' => 'LAUBER',
                'rename_from' => 'CQ',
                'rename_from_bkey' => 'CQ',
                'rename_to' => 'LAUBER',
                'rename_to_bkey' => 'LAUBER',
                'comment' => NULL,
            ),
            
            array (
                'id' => 19,
                'user_id' => 1,
                'name' => 'CONTITECH',
                'bkey' => 'CONTITECH',
                'rename_from' => 'CONTI',
                'rename_from_bkey' => 'CONTI',
                'rename_to' => 'CONTITECH',
                'rename_to_bkey' => 'CONTITECH',
                'comment' => NULL,
            ),
            
            array (
                'id' => 20,
                'user_id' => 1,
                'name' => 'CONTITECH',
                'bkey' => 'CONTITECH',
                'rename_from' => 'CONTI MIECHY',
                'rename_from_bkey' => 'CONTIMIECHY',
                'rename_to' => 'CONTITECH',
                'rename_to_bkey' => 'CONTITECH',
                'comment' => NULL,
            ),
            
            array (
                'id' => 21,
                'user_id' => 1,
                'name' => 'RENAULT',
                'bkey' => 'RENAULT',
                'rename_from' => 'DACIA',
                'rename_from_bkey' => 'DACIA',
                'rename_to' => 'RENAULT',
                'rename_to_bkey' => 'RENAULT',
                'comment' => NULL,
            ),
            
            array (
                'id' => 22,
                'user_id' => 1,
                'name' => 'AUTOMEGA',
                'bkey' => 'AUTOMEGA',
                'rename_from' => 'DELLOAUTOMEGA',
                'rename_from_bkey' => 'DELLOAUTOMEGA',
                'rename_to' => 'AUTOMEGA',
                'rename_to_bkey' => 'AUTOMEGA',
                'comment' => NULL,
            ),
            
            array (
                'id' => 23,
                'user_id' => 1,
                'name' => 'DEPO',
                'bkey' => 'DEPO',
                'rename_from' => 'LORO',
                'rename_from_bkey' => 'LORO',
                'rename_to' => 'DEPO',
                'rename_to_bkey' => 'DEPO',
                'comment' => NULL,
            ),
            
            array (
                'id' => 24,
                'user_id' => 1,
                'name' => 'SERK-MARSTON',
                'bkey' => 'SERKMARSTON',
                'rename_from' => 'ETS',
                'rename_from_bkey' => 'ETS',
                'rename_to' => 'SERK-MARSTON',
                'rename_to_bkey' => 'SERKMARSTON',
                'comment' => NULL,
            ),
            
            array (
                'id' => 25,
                'user_id' => 1,
                'name' => 'RUVILLE',
                'bkey' => 'RUVILLE',
                'rename_from' => 'EVR',
                'rename_from_bkey' => 'EVR',
                'rename_to' => 'RUVILLE',
                'rename_to_bkey' => 'RUVILLE',
                'comment' => NULL,
            ),
            
            array (
                'id' => 26,
                'user_id' => 1,
                'name' => 'FEBI BILSTEIN',
                'bkey' => 'FEBIBILSTEIN',
                'rename_from' => 'FEBIBILSTEIN',
                'rename_from_bkey' => 'FEBIBILSTEIN',
                'rename_to' => 'FEBI BILSTEIN',
                'rename_to_bkey' => 'FEBIBILSTEIN',
                'comment' => NULL,
            ),
            
            array (
                'id' => 27,
                'user_id' => 1,
                'name' => 'FORTUNE LINE',
                'bkey' => 'FORTUNELINE',
                'rename_from' => 'FORTUNA LINE',
                'rename_from_bkey' => 'FORTUNALINE',
                'rename_to' => 'FORTUNE LINE',
                'rename_to_bkey' => 'FORTUNELINE',
                'comment' => NULL,
            ),
            
            array (
                'id' => 28,
                'user_id' => 1,
                'name' => 'FAI AUTOPARTS',
                'bkey' => 'FAIAUTOPARTS',
                'rename_from' => 'FAI',
                'rename_from_bkey' => 'FAI',
                'rename_to' => 'FAI AUTOPARTS',
                'rename_to_bkey' => 'FAIAUTOPARTS',
                'comment' => NULL,
            ),
            
            array (
                'id' => 29,
                'user_id' => 1,
                'name' => 'FISCHER AUTOMOTIVE 1',
                'bkey' => 'FISCHERAUTOMOTIVE1',
                'rename_from' => 'FISCHER',
                'rename_from_bkey' => 'FISCHER',
                'rename_to' => 'FA1',
                'rename_to_bkey' => 'FA1',
                'comment' => NULL,
            ),
            
            array (
                'id' => 30,
                'user_id' => 1,
                'name' => 'FISCHER AUTOMOTIVE 1',
                'bkey' => 'FISCHERAUTOMOTIVE1',
                'rename_from' => 'FISHER',
                'rename_from_bkey' => 'FISHER',
                'rename_to' => 'FA1',
                'rename_to_bkey' => 'FA1',
                'comment' => NULL,
            ),
            
            array (
                'id' => 31,
                'user_id' => 1,
                'name' => 'FAG',
                'bkey' => 'FAG',
                'rename_from' => 'FAGHYDRAULIKA',
                'rename_from_bkey' => 'FAGHYDRAULIKA',
                'rename_to' => 'FAG',
                'rename_to_bkey' => 'FAG',
                'comment' => NULL,
            ),
            
            array (
                'id' => 33,
                'user_id' => 1,
                'name' => 'ORIGINAL IMPERIUM',
                'bkey' => 'ORIGINALIMPERIUM',
                'rename_from' => 'IMPERGOM',
                'rename_from_bkey' => 'IMPERGOM',
                'rename_to' => 'ORIGINAL IMPERIUM',
                'rename_to_bkey' => 'ORIGINALIMPERIUM',
                'comment' => NULL,
            ),
            
            array (
                'id' => 34,
                'user_id' => 1,
                'name' => 'ZIMMERMANN',
                'bkey' => 'ZIMMERMANN',
                'rename_from' => 'OTTO ZIMMERMANN',
                'rename_from_bkey' => 'OTTOZIMMERMANN',
                'rename_to' => 'ZIMMERMANN',
                'rename_to_bkey' => 'ZIMMERMANN',
                'comment' => NULL,
            ),
            
            array (
                'id' => 35,
                'user_id' => 1,
                'name' => 'RENAULT',
                'bkey' => 'RENAULT',
                'rename_from' => 'OE RENAULT',
                'rename_from_bkey' => 'OERENAULT',
                'rename_to' => 'RENAULT',
                'rename_to_bkey' => 'RENAULT',
                'comment' => NULL,
            ),
            
            array (
                'id' => 36,
                'user_id' => 1,
                'name' => 'LADA',
                'bkey' => 'LADA',
                'rename_from' => 'АВТОВАЗ',
                'rename_from_bkey' => 'АВТОВАЗ',
                'rename_to' => 'LADA',
                'rename_to_bkey' => 'LADA',
                'comment' => NULL,
            ),
            
            array (
                'id' => 37,
                'user_id' => 1,
                'name' => 'LADA',
                'bkey' => 'LADA',
                'rename_from' => 'ВАЗ',
                'rename_from_bkey' => 'ВАЗ',
                'rename_to' => 'LADA',
                'rename_to_bkey' => 'LADA',
                'comment' => NULL,
            ),
            
            array (
                'id' => 38,
                'user_id' => 1,
                'name' => 'PE AUTOMOTIVE',
                'bkey' => 'PEAUTOMOTIVE',
                'rename_from' => 'PETERSEN NEPETAL',
                'rename_from_bkey' => 'PETERSENNEPETAL',
                'rename_to' => 'PE AUTOMOTIVE',
                'rename_to_bkey' => 'PEAUTOMOTIVE',
                'comment' => NULL,
            ),
            
            array (
                'id' => 40,
                'user_id' => 1,
                'name' => 'WIX FILTERS',
                'bkey' => 'WIXFILTERS',
                'rename_from' => 'WIX FILTRON',
                'rename_from_bkey' => 'WIXFILTRON',
                'rename_to' => 'WIX FILTERS',
                'rename_to_bkey' => 'WIXFILTERS',
                'comment' => NULL,
            ),
            
            array (
                'id' => 41,
                'user_id' => 1,
                'name' => 'WIX FILTERS',
                'bkey' => 'WIXFILTERS',
                'rename_from' => 'WIX EUROPE',
                'rename_from_bkey' => 'WIXEUROPE',
                'rename_to' => 'WIX FILTERS',
                'rename_to_bkey' => 'WIXFILTERS',
                'comment' => NULL,
            ),
            
            array (
                'id' => 42,
                'user_id' => 1,
                'name' => 'WIX FILTERS',
                'bkey' => 'WIXFILTERS',
                'rename_from' => 'WIX',
                'rename_from_bkey' => 'WIX',
                'rename_to' => 'WIX FILTERS',
                'rename_to_bkey' => 'WIXFILTERS',
                'comment' => NULL,
            ),
            
            array (
                'id' => 43,
                'user_id' => 1,
                'name' => 'RENAULT',
                'bkey' => 'RENAULT',
                'rename_from' => 'RENAU',
                'rename_from_bkey' => 'RENAU',
                'rename_to' => 'RENAULT',
                'rename_to_bkey' => 'RENAULT',
                'comment' => NULL,
            ),
            
            array (
                'id' => 44,
                'user_id' => 1,
                'name' => 'RENAULT',
                'bkey' => 'RENAULT',
                'rename_from' => 'RENAULT-TRUCKS',
                'rename_from_bkey' => 'RENAULTTRUCKS',
                'rename_to' => 'RENAULT',
                'rename_to_bkey' => 'RENAULT',
                'comment' => NULL,
            ),
            
            array (
                'id' => 45,
                'user_id' => 1,
                'name' => 'HENGST FILTER',
                'bkey' => 'HENGSTFILTER',
                'rename_from' => 'HENGST',
                'rename_from_bkey' => 'HENGST',
                'rename_to' => 'HENGST FILTER',
                'rename_to_bkey' => 'HENGSTFILTER',
                'comment' => NULL,
            ),
            
            array (
                'id' => 46,
                'user_id' => 1,
                'name' => 'KLAXCAR FRANCE',
                'bkey' => 'KLAXCARFRANCE',
                'rename_from' => 'KLAXCAR',
                'rename_from_bkey' => 'KLAXCAR',
                'rename_to' => 'KLAXCAR FRANCE',
                'rename_to_bkey' => 'KLAXCARFRANCE',
                'comment' => NULL,
            ),
            
            array (
                'id' => 47,
                'user_id' => 1,
                'name' => 'KYB',
                'bkey' => 'KYB',
                'rename_from' => 'KAYABA',
                'rename_from_bkey' => 'KAYABA',
                'rename_to' => 'KYB',
                'rename_to_bkey' => 'KYB',
                'comment' => NULL,
            ),
            
            array (
                'id' => 48,
                'user_id' => 1,
                'name' => 'FACET',
                'bkey' => 'FACET',
                'rename_from' => 'KW FACET',
                'rename_from_bkey' => 'KWFACET',
                'rename_to' => 'FACET',
                'rename_to_bkey' => 'FACET',
                'comment' => NULL,
            ),
            
            array (
                'id' => 49,
                'user_id' => 1,
                'name' => 'KRAFT AUTOMOTIVE',
                'bkey' => 'KRAFTAUTOMOTIVE',
                'rename_from' => 'KRAFT',
                'rename_from_bkey' => 'KRAFT',
                'rename_to' => 'KRAFT AUTOMOTIVE',
                'rename_to_bkey' => 'KRAFTAUTOMOTIVE',
                'comment' => NULL,
            ),
            
            array (
                'id' => 50,
                'user_id' => 1,
                'name' => 'KOLBENSCHMIDT',
                'bkey' => 'KOLBENSCHMIDT',
                'rename_from' => 'KS',
                'rename_from_bkey' => 'KS',
                'rename_to' => 'KOLBENSCHMIDT',
                'rename_to_bkey' => 'KOLBENSCHMIDT',
                'comment' => NULL,
            ),
            
            array (
                'id' => 51,
                'user_id' => 1,
                'name' => 'KIA',
                'bkey' => 'KIA',
                'rename_from' => 'KIA HYUNDAI',
                'rename_from_bkey' => 'KIAHYUNDAI',
                'rename_to' => 'KIA',
                'rename_to_bkey' => 'KIA',
                'comment' => NULL,
            ),
            
            array (
                'id' => 52,
                'user_id' => 1,
                'name' => 'HYUNDAI',
                'bkey' => 'HYUNDAI',
                'rename_from' => 'HYUNDAI/KIA',
                'rename_from_bkey' => 'HYUNDAIKIA',
                'rename_to' => 'HYUNDAI',
                'rename_to_bkey' => 'HYUNDAI',
                'comment' => NULL,
            ),
            
            array (
                'id' => 53,
                'user_id' => 1,
                'name' => 'KNECHT',
                'bkey' => 'KNECHT',
                'rename_from' => 'KNECHT/MAHLE',
                'rename_from_bkey' => 'KNECHTMAHLE',
                'rename_to' => 'KNECHT',
                'rename_to_bkey' => 'KNECHT',
                'comment' => NULL,
            ),
            
            array (
                'id' => 54,
                'user_id' => 1,
                'name' => 'MAHLE ORIGINAL',
                'bkey' => 'MAHLEORIGINAL',
                'rename_from' => 'MAHLE/KNECHT',
                'rename_from_bkey' => 'MAHLEKNECHT',
                'rename_to' => 'MAHLE ORIGINAL',
                'rename_to_bkey' => 'MAHLEORIGINAL',
                'comment' => NULL,
            ),
            
            array (
                'id' => 55,
                'user_id' => 1,
                'name' => 'MAHLE ORIGINAL',
                'bkey' => 'MAHLEORIGINAL',
                'rename_from' => 'MAHLE',
                'rename_from_bkey' => 'MAHLE',
                'rename_to' => 'MAHLE ORIGINAL',
                'rename_to_bkey' => 'MAHLEORIGINAL',
                'comment' => NULL,
            ),
            
            array (
                'id' => 56,
                'user_id' => 1,
                'name' => 'LADA',
                'bkey' => 'LADA',
                'rename_from' => 'VAZ',
                'rename_from_bkey' => 'VAZ',
                'rename_to' => 'LADA',
                'rename_to_bkey' => 'LADA',
                'comment' => NULL,
            ),
            
            array (
                'id' => 57,
                'user_id' => 1,
                'name' => 'VEMO',
                'bkey' => 'VEMO',
                'rename_from' => 'VEMO-VIEROL',
                'rename_from_bkey' => 'VEMOVIEROL',
                'rename_to' => 'VEMO',
                'rename_to_bkey' => 'VEMO',
                'comment' => NULL,
            ),
            
            array (
                'id' => 58,
                'user_id' => 1,
                'name' => 'VW',
                'bkey' => 'VW',
                'rename_from' => 'VOLKSWAGEN',
                'rename_from_bkey' => 'VOLKSWAGEN',
                'rename_to' => 'VW',
                'rename_to_bkey' => 'VW',
                'comment' => NULL,
            ),
            
            array (
                'id' => 59,
                'user_id' => 1,
                'name' => 'CALORSTAT BY VERNET',
                'bkey' => 'CALORSTATBYVERNET',
                'rename_from' => 'VERNET',
                'rename_from_bkey' => 'VERNET',
                'rename_to' => 'CALORSTAT BY VERNET',
                'rename_to_bkey' => 'CALORSTATBYVERNET',
                'comment' => NULL,
            ),
            
            array (
                'id' => 60,
                'user_id' => 1,
                'name' => 'VAICO',
                'bkey' => 'VAICO',
                'rename_from' => 'VEMO/VAICO',
                'rename_from_bkey' => 'VEMOVAICO',
                'rename_to' => 'VAICO',
                'rename_to_bkey' => 'VAICO',
                'comment' => NULL,
            ),
            
            array (
                'id' => 61,
                'user_id' => 1,
                'name' => 'JAKOPARTS',
                'bkey' => 'JAKOPARTS',
                'rename_from' => 'HERTH+BUSS JAKOPARTS',
                'rename_from_bkey' => 'HERTHBUSSJAKOPARTS',
                'rename_to' => 'JAKOPARTS',
                'rename_to_bkey' => 'JAKOPARTS',
                'comment' => NULL,
            ),
            
            array (
                'id' => 62,
                'user_id' => 1,
                'name' => 'JAKOPARTS',
                'bkey' => 'JAKOPARTS',
                'rename_from' => 'HERTH+BUSS',
                'rename_from_bkey' => 'HERTHBUSS',
                'rename_to' => 'JAKOPARTS',
                'rename_to_bkey' => 'JAKOPARTS',
                'comment' => NULL,
            ),
            
            array (
                'id' => 63,
                'user_id' => 1,
                'name' => 'JAKOPARTS',
                'bkey' => 'JAKOPARTS',
                'rename_from' => 'HERTH+BUSS ELPARTS',
                'rename_from_bkey' => 'HERTHBUSSELPARTS',
                'rename_to' => 'JAKOPARTS',
                'rename_to_bkey' => 'JAKOPARTS',
                'comment' => NULL,
            ),
            
            array (
                'id' => 64,
                'user_id' => 1,
                'name' => 'GE',
                'bkey' => 'GE',
                'rename_from' => 'GENERAL ELECTRIC',
                'rename_from_bkey' => 'GENERALELECTRIC',
                'rename_to' => 'GE',
                'rename_to_bkey' => 'GE',
                'comment' => NULL,
            ),
            
            array (
                'id' => 65,
                'user_id' => 1,
                'name' => 'CHEVROLET',
                'bkey' => 'CHEVROLET',
                'rename_from' => 'GM KOREA',
                'rename_from_bkey' => 'GMKOREA',
                'rename_to' => 'CHEVROLET',
                'rename_to_bkey' => 'CHEVROLET',
                'comment' => NULL,
            ),
            
            array (
                'id' => 66,
                'user_id' => 1,
                'name' => 'GOETZE ENGINE',
                'bkey' => 'GOETZEENGINE',
                'rename_from' => 'GOETZE',
                'rename_from_bkey' => 'GOETZE',
                'rename_to' => 'GOETZE ENGINE',
                'rename_to_bkey' => 'GOETZEENGINE',
                'comment' => NULL,
            ),
            
            array (
                'id' => 67,
                'user_id' => 1,
                'name' => 'LUK',
                'bkey' => 'LUK',
                'rename_from' => 'LUK AFTERMARKET SERVICE OHG',
                'rename_from_bkey' => 'LUKAFTERMARKETSERVICEOHG',
                'rename_to' => 'LUK',
                'rename_to_bkey' => 'LUK',
                'comment' => NULL,
            ),
            
            array (
                'id' => 68,
                'user_id' => 1,
                'name' => 'MERCEDES-BENZ',
                'bkey' => 'MERCEDESBENZ',
                'rename_from' => 'MERCEDES',
                'rename_from_bkey' => 'MERCEDES',
                'rename_to' => 'MERCEDES-BENZ',
                'rename_to_bkey' => 'MERCEDESBENZ',
                'comment' => NULL,
            ),
            
            array (
                'id' => 69,
                'user_id' => 1,
                'name' => 'MERCEDES-BENZ',
                'bkey' => 'MERCEDESBENZ',
                'rename_from' => 'MB',
                'rename_from_bkey' => 'MB',
                'rename_to' => 'MERCEDES-BENZ',
                'rename_to_bkey' => 'MERCEDESBENZ',
                'comment' => NULL,
            ),
            
            array (
                'id' => 70,
                'user_id' => 1,
                'name' => 'GE',
                'bkey' => 'GE',
                'rename_from' => 'TUNGSRAM',
                'rename_from_bkey' => 'TUNGSRAM',
                'rename_to' => 'GE',
                'rename_to_bkey' => 'GE',
                'comment' => NULL,
            ),
            
            array (
                'id' => 71,
                'user_id' => 1,
                'name' => 'TRW',
                'bkey' => 'TRW',
                'rename_from' => 'TRW AUTOMOTIVE',
                'rename_from_bkey' => 'TRWAUTOMOTIVE',
                'rename_to' => 'TRW',
                'rename_to_bkey' => 'TRW',
                'comment' => NULL,
            ),
            
            array (
                'id' => 72,
                'user_id' => 1,
                'name' => 'TOPRAN',
                'bkey' => 'TOPRAN',
                'rename_from' => 'HANS PRIES',
                'rename_from_bkey' => 'HANSPRIES',
                'rename_to' => 'TOPRAN',
                'rename_to_bkey' => 'TOPRAN',
                'comment' => NULL,
            ),
            
            array (
                'id' => 73,
                'user_id' => 1,
                'name' => 'MOBIS',
                'bkey' => 'MOBIS',
                'rename_from' => 'HYUNDAI/KIA/MOBIS',
                'rename_from_bkey' => 'HYUNDAIKIAMOBIS',
                'rename_to' => 'MOBIS',
                'rename_to_bkey' => 'MOBIS',
                'comment' => NULL,
            ),
            
            array (
                'id' => 74,
                'user_id' => 1,
                'name' => 'HALDEX',
                'bkey' => 'HALDEX',
                'rename_from' => 'HALDEX2',
                'rename_from_bkey' => 'HALDEX2',
                'rename_to' => 'HALDEX',
                'rename_to_bkey' => 'HALDEX',
                'comment' => NULL,
            ),
            
            array (
                'id' => 76,
                'user_id' => 1,
                'name' => 'LEMFORDER',
                'bkey' => 'LEMFORDER',
                'rename_from' => 'LEMFOERDER',
                'rename_from_bkey' => 'LEMFOERDER',
                'rename_to' => 'LEMFÖRDER',
                'rename_to_bkey' => 'LEMFORDER',
                'comment' => NULL,
            ),
            
            array (
                'id' => 78,
                'user_id' => 1,
                'name' => 'LEMFORDER',
                'bkey' => 'LEMFORDER',
                'rename_from' => 'LMI',
                'rename_from_bkey' => 'LMI',
                'rename_to' => 'LEMFÖRDER',
                'rename_to_bkey' => 'LEMFORDER',
                'comment' => NULL,
            ),
            
            array (
                'id' => 79,
                'user_id' => 1,
                'name' => 'LEMFORDER',
                'bkey' => 'LEMFORDER',
                'rename_from' => 'LEMF',
                'rename_from_bkey' => 'LEMF',
                'rename_to' => 'LEMFÖRDER',
                'rename_to_bkey' => 'LEMFORDER',
                'comment' => NULL,
            ),
            
            array (
                'id' => 80,
                'user_id' => 1,
                'name' => 'MAHLE ORIGINAL',
                'bkey' => 'MAHLEORIGINAL',
                'rename_from' => 'MAHLE FILTERS',
                'rename_from_bkey' => 'MAHLEFILTERS',
                'rename_to' => 'MAHLE ORIGINAL',
                'rename_to_bkey' => 'MAHLEORIGINAL',
                'comment' => NULL,
            ),
            
            array (
                'id' => 81,
                'user_id' => 1,
                'name' => 'MAHLE ORIGINAL',
                'bkey' => 'MAHLEORIGINAL',
                'rename_from' => 'MAHLE FILTER',
                'rename_from_bkey' => 'MAHLEFILTER',
                'rename_to' => 'MAHLE ORIGINAL',
                'rename_to_bkey' => 'MAHLEORIGINAL',
                'comment' => NULL,
            ),
            
            array (
                'id' => 82,
                'user_id' => 1,
                'name' => 'MANN FILTER',
                'bkey' => 'MANNFILTER',
                'rename_from' => 'MANN+HUMMEL',
                'rename_from_bkey' => 'MANNHUMMEL',
                'rename_to' => 'MANN FILTER',
                'rename_to_bkey' => 'MANNFILTER',
                'comment' => NULL,
            ),
            
            array (
                'id' => 83,
                'user_id' => 1,
                'name' => 'MANN FILTER',
                'bkey' => 'MANNFILTER',
                'rename_from' => 'MANN',
                'rename_from_bkey' => 'MANN',
                'rename_to' => 'MANN FILTER',
                'rename_to_bkey' => 'MANNFILTER',
                'comment' => NULL,
            ),
            
            array (
                'id' => 84,
                'user_id' => 1,
                'name' => 'SACHS',
                'bkey' => 'SACHS',
                'rename_from' => 'SACHS2',
                'rename_from_bkey' => 'SACHS2',
                'rename_to' => 'SACHS',
                'rename_to_bkey' => 'SACHS',
                'comment' => NULL,
            ),
            
            array (
                'id' => 85,
                'user_id' => 1,
                'name' => 'VDO',
                'bkey' => 'VDO',
                'rename_from' => 'SIEMENS VDO',
                'rename_from_bkey' => 'SIEMENSVDO',
                'rename_to' => 'VDO',
                'rename_to_bkey' => 'VDO',
                'comment' => NULL,
            ),
            
            array (
                'id' => 86,
                'user_id' => 1,
                'name' => 'SCT',
                'bkey' => 'SCT',
                'rename_from' => 'SCTGERMANY',
                'rename_from_bkey' => 'SCTGERMANY',
                'rename_to' => 'SCT',
                'rename_to_bkey' => 'SCT',
                'comment' => NULL,
            ),
            
            array (
                'id' => 87,
                'user_id' => 1,
                'name' => 'SAKURA',
                'bkey' => 'SAKURA',
                'rename_from' => 'SAKURA AUTOMOTIVE',
                'rename_from_bkey' => 'SAKURAAUTOMOTIVE',
                'rename_to' => 'SAKURA',
                'rename_to_bkey' => 'SAKURA',
                'comment' => NULL,
            ),
            
            array (
                'id' => 88,
                'user_id' => 1,
                'name' => 'CIFAM',
                'bkey' => 'CIFAM',
                'rename_from' => 'METELLI CIFAM',
                'rename_from_bkey' => 'METELLICIFAM',
                'rename_to' => 'CIFAM',
                'rename_to_bkey' => 'CIFAM',
                'comment' => NULL,
            ),
            
            array (
                'id' => 89,
                'user_id' => 1,
                'name' => 'MAGNETTI MARELLI',
                'bkey' => 'MAGNETTIMARELLI',
                'rename_from' => 'MMARELLI',
                'rename_from_bkey' => 'MMARELLI',
                'rename_to' => 'MAGNETTI MARELLI',
                'rename_to_bkey' => 'MAGNETTIMARELLI',
                'comment' => NULL,
            ),
            
            array (
                'id' => 90,
                'user_id' => 1,
                'name' => 'MAGNETTI MARELLI',
                'bkey' => 'MAGNETTIMARELLI',
                'rename_from' => 'MAGNETTI MARELLI BR',
                'rename_from_bkey' => 'MAGNETTIMARELLIBR',
                'rename_to' => 'MAGNETTI MARELLI',
                'rename_to_bkey' => 'MAGNETTIMARELLI',
                'comment' => NULL,
            ),
            
            array (
                'id' => 91,
                'user_id' => 1,
                'name' => 'SNR',
                'bkey' => 'SNR',
                'rename_from' => 'NTN/SNR',
                'rename_from_bkey' => 'NTNSNR',
                'rename_to' => 'SNR',
                'rename_to_bkey' => 'SNR',
                'comment' => NULL,
            ),
            
            array (
                'id' => 92,
                'user_id' => 1,
                'name' => 'NISSAN',
                'bkey' => 'NISSAN',
                'rename_from' => 'NISSAN DONGFENG',
                'rename_from_bkey' => 'NISSANDONGFENG',
                'rename_to' => 'NISSAN',
                'rename_to_bkey' => 'NISSAN',
                'comment' => NULL,
            ),
            
            array (
                'id' => 93,
                'user_id' => 1,
                'name' => 'SPIDAN',
                'bkey' => 'SPIDAN',
                'rename_from' => 'SPIDAN/GKN',
                'rename_from_bkey' => 'SPIDANGKN',
                'rename_to' => 'SPIDAN',
                'rename_to_bkey' => 'SPIDAN',
                'comment' => NULL,
            ),
            
            array (
                'id' => 94,
                'user_id' => 1,
                'name' => 'TRISCAN',
                'bkey' => 'TRISCAN',
                'rename_from' => 'TRISCUN',
                'rename_from_bkey' => 'TRISCUN',
                'rename_to' => 'TRISCAN',
                'rename_to_bkey' => 'TRISCAN',
                'comment' => NULL,
            ),
            
            array (
                'id' => 95,
                'user_id' => 1,
                'name' => 'TECNODELTA',
                'bkey' => 'TECNODELTA',
                'rename_from' => 'NUOVA TECNODELTA',
                'rename_from_bkey' => 'NUOVATECNODELTA',
                'rename_to' => 'TECNODELTA',
                'rename_to_bkey' => 'TECNODELTA',
                'comment' => NULL,
            ),
            
            array (
                'id' => 96,
                'user_id' => 1,
                'name' => 'VALEO',
                'bkey' => 'VALEO',
                'rename_from' => 'VALEOWYCIERACZKI',
                'rename_from_bkey' => 'VALEOWYCIERACZKI',
                'rename_to' => 'VALEO',
                'rename_to_bkey' => 'VALEO',
                'comment' => NULL,
            ),
            
            array (
                'id' => 97,
                'user_id' => 1,
                'name' => 'VICTOR REINZ',
                'bkey' => 'VICTORREINZ',
                'rename_from' => 'VICTREINZ',
                'rename_from_bkey' => 'VICTREINZ',
                'rename_to' => 'VICTOR REINZ',
                'rename_to_bkey' => 'VICTORREINZ',
                'comment' => NULL,
            ),
            
            array (
                'id' => 98,
                'user_id' => 1,
                'name' => 'VICTOR REINZ',
                'bkey' => 'VICTORREINZ',
                'rename_from' => 'REINZ',
                'rename_from_bkey' => 'REINZ',
                'rename_to' => 'VICTOR REINZ',
                'rename_to_bkey' => 'VICTORREINZ',
                'comment' => NULL,
            ),
            
            array (
                'id' => 99,
                'user_id' => 1,
                'name' => 'VALEO',
                'bkey' => 'VALEO',
                'rename_from' => 'VALEO2',
                'rename_from_bkey' => 'VALEO2',
                'rename_to' => 'VALEO',
                'rename_to_bkey' => 'VALEO',
                'comment' => NULL,
            ),
            
            array (
                'id' => 100,
                'user_id' => 1,
                'name' => 'VW',
                'bkey' => 'VW',
                'rename_from' => 'VW/SEAT',
                'rename_from_bkey' => 'VWSEAT',
                'rename_to' => 'VW',
                'rename_to_bkey' => 'VW',
                'comment' => NULL,
            ),
            
            array (
                'id' => 101,
                'user_id' => 1,
                'name' => 'ASP MENSAN',
                'bkey' => 'ASPMENSAN',
                'rename_from' => 'MENSAN',
                'rename_from_bkey' => 'MENSAN',
                'rename_to' => 'ASP MENSAN',
                'rename_to_bkey' => 'ASPMENSAN',
                'comment' => NULL,
            ),
            
            array (
                'id' => 102,
                'user_id' => 1,
                'name' => 'ASP MENSAN',
                'bkey' => 'ASPMENSAN',
                'rename_from' => 'ASP',
                'rename_from_bkey' => 'ASP',
                'rename_to' => 'ASP MENSAN',
                'rename_to_bkey' => 'ASPMENSAN',
                'comment' => NULL,
            ),
            
            array (
                'id' => 103,
                'user_id' => 1,
                'name' => 'LYNX AUTO',
                'bkey' => 'LYNXAUTO',
                'rename_from' => 'LYNX',
                'rename_from_bkey' => 'LYNX',
                'rename_to' => 'LYNXAUTO',
                'rename_to_bkey' => 'LYNXAUTO',
                'comment' => NULL,
            ),
            
            array (
                'id' => 104,
                'user_id' => 1,
                'name' => 'LEMFORDER',
                'bkey' => 'LEMFORDER',
                'rename_from' => 'LEMF RDER',
                'rename_from_bkey' => 'LEMFRDER',
                'rename_to' => 'LEMFÖRDER',
                'rename_to_bkey' => 'LEMFORDER',
                'comment' => NULL,
            ),
            
            array (
                'id' => 105,
                'user_id' => 1,
                'name' => 'FEBI BILSTEIN',
                'bkey' => 'FEBIBILSTEIN',
                'rename_from' => 'FEBI',
                'rename_from_bkey' => 'FEBI',
                'rename_to' => 'FEBI BILSTEIN',
                'rename_to_bkey' => 'FEBIBILSTEIN',
                'comment' => NULL,
            ),
            
            array (
                'id' => 106,
                'user_id' => 1,
                'name' => 'NISSAN',
                'bkey' => 'NISSAN',
                'rename_from' => 'NISSAN/INFINITI',
                'rename_from_bkey' => 'NISSANINFINITI',
                'rename_to' => 'NISSAN',
                'rename_to_bkey' => 'NISSAN',
                'comment' => NULL,
            ),
            
            array (
                'id' => 107,
                'user_id' => 1,
                'name' => 'RENAULT',
                'bkey' => 'RENAULT',
                'rename_from' => 'RVI',
                'rename_from_bkey' => 'RVI',
                'rename_to' => 'RENAULT',
                'rename_to_bkey' => 'RENAULT',
                'comment' => NULL,
            ),
        ));
        
        
    }
}