<?php

use Illuminate\Database\Seeder;

class DatabaseSeeder extends Seeder
{
    public function run()
    {

        $this->call(AdminCartsTableSeeder::class);
        $this->call(BlogCategoriesTableSeeder::class);
        $this->call(BlogPostsTableSeeder::class);
        $this->call(BlogPostsCommentsTableSeeder::class);
        $this->call(BlogPostsTagsTableSeeder::class);
        $this->call(BlogTagsTableSeeder::class);
        $this->call(BrandRenamesTableSeeder::class);
        $this->call(BrandsTableSeeder::class);
        $this->call(BrandsRatingsTableSeeder::class);
        $this->call(CatalogGroupsTableSeeder::class);
        $this->call(ClientAddressesTableSeeder::class);
        $this->call(ClientAutoColorsTableSeeder::class);
        $this->call(ClientAutoServicePartsTableSeeder::class);
        $this->call(ClientAutosTableSeeder::class);
        $this->call(ClientOrderCorrectionsTableSeeder::class);
        $this->call(ClientOrdersTableSeeder::class);
        $this->call(ClientPhonesTableSeeder::class);
        $this->call(ClientsTableSeeder::class);
        $this->call(CouponsTableSeeder::class);
        $this->call(CurrenciesTableSeeder::class);
        $this->call(EmployeesTableSeeder::class);
        $this->call(FailedJobsTableSeeder::class);
        $this->call(InventorySettingsTableSeeder::class);
        $this->call(MigrationsTableSeeder::class);
        $this->call(ModelUrlsTableSeeder::class);
        $this->call(OnlineOrderHistoriesTableSeeder::class);
        $this->call(OnlineOrderProductsTableSeeder::class);
        $this->call(OnlineOrdersTableSeeder::class);
        $this->call(OrderStatusesTableSeeder::class);
        $this->call(PasswordResetsTableSeeder::class);
        $this->call(PaymentMethodsTableSeeder::class);
        $this->call(PayrollEmployeesTableSeeder::class);
        $this->call(PayrollsTableSeeder::class);
        $this->call(PricetypesTableSeeder::class);
        $this->call(ProductAdminCartsTableSeeder::class);
        $this->call(ProductCategoriesTableSeeder::class);
        $this->call(ProductClientOrderControlTableSeeder::class);
        $this->call(ProductClientOrderCorrectionsTableSeeder::class);
        $this->call(ProductClientOrdersTableSeeder::class);
        $this->call(ProductClientToProviderOrderControlTableSeeder::class);
        $this->call(ProductClientToProviderOrdersTableSeeder::class);
        $this->call(ProductCrossesTableSeeder::class);
        $this->call(ProductGroupsTableSeeder::class);
        $this->call(ProductMinimalStocksTableSeeder::class);
        $this->call(ProductOrderManagementTableSeeder::class);
        $this->call(ProductPriceGroupsTableSeeder::class);
        $this->call(ProductPricesTableSeeder::class);
        $this->call(ProductRatingsTableSeeder::class);
        $this->call(ProductRepairOrdersTableSeeder::class);
        $this->call(ProductReturnsFromTheClientTableSeeder::class);
        $this->call(ProductReturnsToProviderTableSeeder::class);
        $this->call(ProductStocksTableSeeder::class);
        $this->call(ProductToProviderOrderControlTableSeeder::class);
        $this->call(ProductToProviderOrdersTableSeeder::class);
        $this->call(ProductsTableSeeder::class);
        $this->call(ProviderPriceColumnsTableSeeder::class);
        $this->call(ProviderPricesTableSeeder::class);
        $this->call(ProviderWebserviceCounterTableSeeder::class);
        $this->call(ProviderWebserviceTimeTableSeeder::class);
        $this->call(ProvidersTableSeeder::class);
        $this->call(ReceiptsTableSeeder::class);
        $this->call(ReceivedProductsTableSeeder::class);
        $this->call(RepairOrdersTableSeeder::class);
        $this->call(ReturnsFromTheClientTableSeeder::class);
        $this->call(ReturnsToProviderTableSeeder::class);
        $this->call(SalaryManagementTableSeeder::class);
        $this->call(SalaryPaymentEmployeesTableSeeder::class);
        $this->call(SalaryPaymentsTableSeeder::class);
        $this->call(SalesTableSeeder::class);
        $this->call(SectionseoTableSeeder::class);
        $this->call(ServiceRepairOrdersTableSeeder::class);
        $this->call(ServicesTableSeeder::class);
        $this->call(ServicesReceiptItemsTableSeeder::class);
        $this->call(ServicesReceiptsTableSeeder::class);
        $this->call(SettlementsTableSeeder::class);
        $this->call(ShopMessageSubjectsTableSeeder::class);
        $this->call(ShopMessagesTableSeeder::class);
        $this->call(ShopSettingsTableSeeder::class);
        $this->call(SoldProductsTableSeeder::class);
        $this->call(SpecialBatteriesTableSeeder::class);
        $this->call(SpecialOilsTableSeeder::class);
        $this->call(SpecialRimsTableSeeder::class);
        $this->call(SpecialToolsTableSeeder::class);
        $this->call(SpecialTyresTableSeeder::class);
        $this->call(TestimonialsTableSeeder::class);
        $this->call(ToProviderOrdersTableSeeder::class);
        $this->call(TransactionsTableSeeder::class);
        $this->call(TransfersTableSeeder::class);
        $this->call(UsersTableSeeder::class);
        $this->call(WarehousesTableSeeder::class);
    }
}
