<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class OnlineOrderProductsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('online_order_products')->delete();
        
        \DB::table('online_order_products')->insert(array (
            
            array (
                'id' => 6,
                'online_order_id' => 9,
                'product_uid' => '',
                'name' => 'Ремень 13A0675C',
                'model' => 'DAYCO_13A0675C',
                'quantity' => '1.00',
                'price' => '540.00',
                'provider_price' => '540.00',
                'provider_currency' => 'RUB',
                'total' => '540.00',
                'tax' => '0.00',
                'reward' => '0.00',
                'article' => '13A0675C',
                'brand' => 'DAYCO',
                'bkey' => 'DAYCO',
                'akey' => '13A0675C',
                'pkey' => 'DAYCO13A0675C',
                'provider' => 'AVT',
                'stock' => 'Москва::14.02.2024',
                'options' => '0;0;0;0;0;0;0;0;0;0;0;0;0;0;',
                'day' => 6,
                'code' => 'AVT',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            
            array (
                'id' => 7,
                'online_order_id' => 9,
                'product_uid' => '',
                'name' => 'Ремень поликлиновой Citroen  Fiat  Honda  Hyundai  Kia  Mazda  Nissan  Peugeot  Rover  Suba',
                'model' => 'DAYCO_4PK812',
                'quantity' => '1.00',
                'price' => '550.00',
                'provider_price' => '550.00',
                'provider_currency' => 'RUB',
                'total' => '550.00',
                'tax' => '0.00',
                'reward' => '0.00',
                'article' => '4PK812',
                'brand' => 'DAYCO',
                'bkey' => 'DAYCO',
                'akey' => '4PK812',
                'pkey' => 'DAYCO4PK812',
                'provider' => 'AVT',
                'stock' => 'Москва::14.02.2024',
                'options' => '0;0;0;0;0;0;0;0;0;0;0;0;0;0;',
                'day' => 6,
                'code' => 'AVT',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            
            array (
                'id' => 8,
                'online_order_id' => 9,
                'product_uid' => '',
                'name' => 'РЕМЕНЬ ПОЛИКЛИНОВЫЙ BMW 5 03- 7 03- HON CIVIC V 94-96 CIVIC VI 95-01 CR-V I 95-02 HR-V 99- SUB LEGAC',
                'model' => 'DAYCO_4PK845',
                'quantity' => '1.00',
                'price' => '625.00',
                'provider_price' => '625.00',
                'provider_currency' => 'RUB',
                'total' => '625.00',
                'tax' => '0.00',
                'reward' => '0.00',
                'article' => '4PK845',
                'brand' => 'DAYCO',
                'bkey' => 'DAYCO',
                'akey' => '4PK845',
                'pkey' => 'DAYCO4PK845',
                'provider' => 'AVT',
                'stock' => 'Москва::14.02.2024',
                'options' => '0;0;0;0;0;0;0;0;0;0;0;0;0;0;',
                'day' => 6,
                'code' => 'AVT',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            
            array (
                'id' => 9,
                'online_order_id' => 9,
                'product_uid' => '',
                'name' => 'Ролик приводного ремня натяжителя HYUNDAI ACCENT ELANTRA I30 KIA CEED RIO SOUL 1,3-2,0',
                'model' => 'GMB_GTA0740',
                'quantity' => '1.00',
                'price' => '875.00',
                'provider_price' => '875.00',
                'provider_currency' => 'RUB',
                'total' => '875.00',
                'tax' => '0.00',
                'reward' => '0.00',
                'article' => 'GTA0740',
                'brand' => 'GMB',
                'bkey' => 'GMB',
                'akey' => 'GTA0740',
                'pkey' => 'GMBGTA0740',
                'provider' => 'AVT',
                'stock' => 'Москва::14.02.2024',
                'options' => '0;0;0;0;0;0;0;0;0;0;0;0;0;0;',
                'day' => 6,
                'code' => 'AVT',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            
            array (
                'id' => 10,
                'online_order_id' => 10,
                'product_uid' => '',
                'name' => 'фильтр масляный',
                'model' => 'MANNFILTER_HU7020Z',
                'quantity' => '2.00',
                'price' => '1455.00',
                'provider_price' => '1455.00',
                'provider_currency' => 'RUB',
                'total' => '2910.00',
                'tax' => '0.00',
                'reward' => '0.00',
                'article' => 'HU7020Z',
                'brand' => 'MANN-FILTER',
                'bkey' => 'MANNFILTER',
                'akey' => 'HU7020Z',
                'pkey' => 'MANNFILTERHU7020Z',
                'provider' => 'AVT',
                'stock' => 'Москва::24.02.2024',
                'options' => '0;0;0;0;0;0;0;0;0;0;0;0;0;0;',
                'day' => 4,
                'code' => 'AVT',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            
            array (
                'id' => 11,
                'online_order_id' => 11,
                'product_uid' => '',
                'name' => 'Амортизатор Isuzu Trooper',
                'model' => 'TOKICO_3418',
                'quantity' => '2.00',
                'price' => '1780.00',
                'provider_price' => '1780.00',
                'provider_currency' => 'RUB',
                'total' => '3560.00',
                'tax' => '0.00',
                'reward' => '0.00',
                'article' => '3418',
                'brand' => 'TOKICO',
                'bkey' => 'TOKICO',
                'akey' => '3418',
                'pkey' => 'TOKICO3418',
                'provider' => 'MKD',
                'stock' => 'RD2',
                'options' => '0;0;0;0;0;0;0;0;0;0;0;100;0;0;',
                'day' => 1,
                'code' => 'MKD',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
            
            array (
                'id' => 12,
                'online_order_id' => 11,
                'product_uid' => '',
                'name' => 'Амортизатор Isuzu Trooper',
                'model' => 'TOKICO_3418',
                'quantity' => '1.00',
                'price' => '1422.53',
                'provider_price' => '1422.53',
                'provider_currency' => 'RUB',
                'total' => '1422.53',
                'tax' => '0.00',
                'reward' => '0.00',
                'article' => '3418',
                'brand' => 'TOKICO',
                'bkey' => 'TOKICO',
                'akey' => '3418',
                'pkey' => 'TOKICO3418',
                'provider' => 'MKD',
                'stock' => 'MAK',
                'options' => '0;0;0;0;0;0;0;0;0;0;0;100;0;0;',
                'day' => 1,
                'code' => 'MKD',
                'created_at' => NULL,
                'updated_at' => NULL,
                'deleted_at' => NULL,
            ),
        ));
        
        
    }
}