<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class SpecialRimsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('special_rims')->delete();
        
        \DB::table('special_rims')->insert(array (
            
            array (
                'id' => 32,
                'article' => 'BKR-060',
                'akey' => 'BKR060',
                'brand' => 'RENAULT',
                'bkey' => 'RENAULT',
                'model' => '',
                'width' => '5,5',
                'size' => 'R14',
                'bolt_hole_circle' => '100',
                'rim_hole_number' => '4',
                'offset' => 'ET43',
                'material' => 'Алюминий',
                'product_line' => 'NULL',
                'colour' => 'Silver',
                'centering_diameter' => 'D60,1',
                'condition' => 'NULL',
                'ean' => '0',
                'image' => 'NULL',
                'type' => '',
            ),
            
            array (
                'id' => 33,
                'article' => 'BKR-079',
                'akey' => 'BKR079',
                'brand' => 'RENAULT',
                'bkey' => 'RENAULT',
                'model' => '',
                'width' => '5,5',
                'size' => 'R14',
                'bolt_hole_circle' => '100',
                'rim_hole_number' => '4',
                'offset' => 'ET43',
                'material' => 'Алюминий',
                'product_line' => 'NULL',
                'colour' => 'Silver',
                'centering_diameter' => 'D60,1',
                'condition' => 'NULL',
                'ean' => '0',
                'image' => 'NULL',
                'type' => '',
            ),
            
            array (
                'id' => 34,
                'article' => 'YQR-059',
                'akey' => 'YQR059',
                'brand' => 'RENAULT',
                'bkey' => 'RENAULT',
                'model' => '',
                'width' => '5,5',
                'size' => 'R14',
                'bolt_hole_circle' => '100',
                'rim_hole_number' => '4',
                'offset' => 'ET43',
                'material' => 'Алюминий',
                'product_line' => 'NULL',
                'colour' => 'Silver',
                'centering_diameter' => 'D60,1',
                'condition' => 'NULL',
                'ean' => '0',
                'image' => 'NULL',
                'type' => '',
            ),
            
            array (
                'id' => 35,
                'article' => 'ATR-730',
                'akey' => 'ATR730',
                'brand' => 'RENAULT',
                'bkey' => 'RENAULT',
                'model' => '',
                'width' => '5,5',
                'size' => 'R14',
                'bolt_hole_circle' => '100',
                'rim_hole_number' => '4',
                'offset' => 'ET45',
                'material' => 'Алюминий',
                'product_line' => 'NULL',
                'colour' => 'Silver',
                'centering_diameter' => 'D60,1',
                'condition' => 'NULL',
                'ean' => '0',
                'image' => 'NULL',
                'type' => '',
            ),
            
            array (
                'id' => 36,
                'article' => 'BKR-167',
                'akey' => 'BKR167',
                'brand' => 'RENAULT',
                'bkey' => 'RENAULT',
                'model' => '',
                'width' => '6',
                'size' => 'R14',
                'bolt_hole_circle' => '100',
                'rim_hole_number' => '4',
                'offset' => 'ET35',
                'material' => 'Алюминий',
                'product_line' => 'NULL',
                'colour' => 'Silver',
                'centering_diameter' => 'D60,1',
                'condition' => 'NULL',
                'ean' => '0',
                'image' => 'NULL',
                'type' => '',
            ),
            
            array (
                'id' => 37,
                'article' => 'BKR-648',
                'akey' => 'BKR648',
                'brand' => 'RENAULT',
                'bkey' => 'RENAULT',
                'model' => '',
                'width' => '6',
                'size' => 'R14',
                'bolt_hole_circle' => '100',
                'rim_hole_number' => '4',
                'offset' => 'ET36',
                'material' => 'Алюминий',
                'product_line' => 'NULL',
                'colour' => 'HS',
                'centering_diameter' => 'D60,1',
                'condition' => 'NULL',
                'ean' => '0',
                'image' => 'NULL',
                'type' => '',
            ),
            
            array (
                'id' => 38,
                'article' => 'ATR-730',
                'akey' => 'ATR730',
                'brand' => 'RENAULT',
                'bkey' => 'RENAULT',
                'model' => '',
                'width' => '5,5',
                'size' => 'R15',
                'bolt_hole_circle' => '100',
                'rim_hole_number' => '4',
                'offset' => 'ET45',
                'material' => 'Алюминий',
                'product_line' => 'NULL',
                'colour' => 'Silver',
                'centering_diameter' => 'D60,1',
                'condition' => 'NULL',
                'ean' => '0',
                'image' => 'NULL',
                'type' => '',
            ),
            
            array (
                'id' => 39,
                'article' => 'ATR-415',
                'akey' => 'ATR415',
                'brand' => 'RENAULT',
                'bkey' => 'RENAULT',
                'model' => '',
                'width' => '5,5',
                'size' => 'R15',
                'bolt_hole_circle' => '100',
                'rim_hole_number' => '4',
                'offset' => 'ET50',
                'material' => 'Алюминий',
                'product_line' => 'NULL',
                'colour' => 'SP',
                'centering_diameter' => 'D60,1',
                'condition' => 'NULL',
                'ean' => '0',
                'image' => 'NULL',
                'type' => '',
            ),
            
            array (
                'id' => 40,
                'article' => 'ATR-809',
                'akey' => 'ATR809',
                'brand' => 'RENAULT',
                'bkey' => 'RENAULT',
                'model' => '',
                'width' => '5,5',
                'size' => 'R15',
                'bolt_hole_circle' => '100',
                'rim_hole_number' => '4',
                'offset' => 'ET50',
                'material' => 'Алюминий',
                'product_line' => 'NULL',
                'colour' => 'Silver',
                'centering_diameter' => 'D60,1',
                'condition' => 'NULL',
                'ean' => '0',
                'image' => 'NULL',
                'type' => '',
            ),
            
            array (
                'id' => 41,
                'article' => 'BKR-587',
                'akey' => 'BKR587',
                'brand' => 'RENAULT',
                'bkey' => 'RENAULT',
                'model' => '',
                'width' => '6,5',
                'size' => 'R15',
                'bolt_hole_circle' => '114,3',
                'rim_hole_number' => '5',
                'offset' => 'ET43',
                'material' => 'Алюминий',
                'product_line' => 'NULL',
                'colour' => 'Silver',
                'centering_diameter' => 'D66,1',
                'condition' => 'NULL',
                'ean' => '0',
                'image' => 'NULL',
                'type' => '',
            ),
            
            array (
                'id' => 42,
                'article' => 'ATR-5068',
                'akey' => 'ATR5068',
                'brand' => 'RENAULT',
                'bkey' => 'RENAULT',
                'model' => '',
                'width' => '6,5',
                'size' => 'R16',
                'bolt_hole_circle' => '114,3',
                'rim_hole_number' => '5',
                'offset' => 'ET40',
                'material' => 'Алюминий',
                'product_line' => 'NULL',
                'colour' => 'HB',
                'centering_diameter' => 'D66,1',
                'condition' => 'NULL',
                'ean' => '0',
                'image' => 'NULL',
                'type' => '',
            ),
            
            array (
                'id' => 43,
                'article' => 'SLR-221',
                'akey' => 'SLR221',
                'brand' => 'RENAULT',
                'bkey' => 'RENAULT',
                'model' => '',
                'width' => '6,5',
                'size' => 'R16',
                'bolt_hole_circle' => '114,3',
                'rim_hole_number' => '5',
                'offset' => 'ET46',
                'material' => 'Алюминий',
                'product_line' => 'NULL',
                'colour' => 'Silver',
                'centering_diameter' => 'D67,1',
                'condition' => 'NULL',
                'ean' => '0',
                'image' => 'NULL',
                'type' => '',
            ),
            
            array (
                'id' => 44,
                'article' => 'YQR-233',
                'akey' => 'YQR233',
                'brand' => 'RENAULT',
                'bkey' => 'RENAULT',
                'model' => '',
                'width' => '6,5',
                'size' => 'R16',
                'bolt_hole_circle' => '114,3',
                'rim_hole_number' => '5',
                'offset' => 'ET47',
                'material' => 'Алюминий',
                'product_line' => 'NULL',
                'colour' => 'HS',
                'centering_diameter' => 'D66,1',
                'condition' => 'NULL',
                'ean' => '0',
                'image' => 'NULL',
                'type' => '',
            ),
            
            array (
                'id' => 45,
                'article' => 'YQR-061',
                'akey' => 'YQR061',
                'brand' => 'RENAULT',
                'bkey' => 'RENAULT',
                'model' => '',
                'width' => '6,5',
                'size' => 'R17',
                'bolt_hole_circle' => '114,3',
                'rim_hole_number' => '5',
                'offset' => 'ET40',
                'material' => 'Алюминий',
                'product_line' => 'NULL',
                'colour' => 'Silver',
                'centering_diameter' => 'D66',
                'condition' => 'NULL',
                'ean' => '0',
                'image' => 'NULL',
                'type' => '',
            ),
            
            array (
                'id' => 46,
                'article' => 'YQR-061',
                'akey' => 'YQR061',
                'brand' => 'RENAULT',
                'bkey' => 'RENAULT',
                'model' => '',
                'width' => '6,5',
                'size' => 'R17',
                'bolt_hole_circle' => '114,3',
                'rim_hole_number' => '5',
                'offset' => 'ET40',
                'material' => 'Алюминий',
                'product_line' => 'NULL',
                'colour' => 'Silver',
                'centering_diameter' => 'D66',
                'condition' => 'NULL',
                'ean' => '0',
                'image' => 'NULL',
                'type' => '',
            ),
            
            array (
                'id' => 47,
                'article' => 'WR-634',
                'akey' => 'WR634',
                'brand' => 'RENAULT',
                'bkey' => 'RENAULT',
                'model' => '',
                'width' => '7',
                'size' => 'R17',
                'bolt_hole_circle' => '114,3',
                'rim_hole_number' => '5',
                'offset' => 'ET40',
                'material' => 'Алюминий',
                'product_line' => 'NULL',
                'colour' => 'Silver',
                'centering_diameter' => 'D66,1',
                'condition' => 'NULL',
                'ean' => '0',
                'image' => 'NULL',
                'type' => '',
            ),
        ));
        
        
    }
}