<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class ToProviderOrdersTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('to_provider_orders')->delete();
        
        \DB::table('to_provider_orders')->insert(array (
            
            array (
                'id' => 14,
                'provider_id' => 2,
                'barcode' => NULL,
                'user_id' => 1,
                'warehouse_id' => 1,
                'currency' => 'RUB',
                'total_quantity' => 2,
                'total_amount' => '0.00',
                'reference_type' => 'client_order',
                'reference_id' => 3,
                'finalized_at' => '2023-09-27 05:41:50',
                'created_at' => '2023-09-27 05:35:23',
                'updated_at' => '2023-09-27 05:41:50',
                'deleted_at' => NULL,
                'comment' => NULL,
            ),
            
            array (
                'id' => 15,
                'provider_id' => 5,
                'barcode' => '2023 10 02 000005',
                'user_id' => 1,
                'warehouse_id' => 1,
                'currency' => 'RUB',
                'total_quantity' => 1,
                'total_amount' => '0.00',
                'reference_type' => 'client_order',
                'reference_id' => 5,
                'finalized_at' => '2023-10-02 11:01:28',
                'created_at' => '2023-10-02 11:01:22',
                'updated_at' => '2023-10-02 11:01:28',
                'deleted_at' => NULL,
                'comment' => NULL,
            ),
            
            array (
                'id' => 16,
                'provider_id' => 5,
                'barcode' => '2023 10 05 000005',
                'user_id' => 1,
                'warehouse_id' => 1,
                'currency' => 'RUB',
                'total_quantity' => 3,
                'total_amount' => '0.00',
                'reference_type' => 'client_order',
                'reference_id' => 6,
                'finalized_at' => '2023-10-05 17:05:16',
                'created_at' => '2023-10-05 17:03:57',
                'updated_at' => '2023-10-05 17:05:16',
                'deleted_at' => NULL,
                'comment' => NULL,
            ),
            
            array (
                'id' => 17,
                'provider_id' => 2,
                'barcode' => '2023 10 06 000002',
                'user_id' => 1,
                'warehouse_id' => 1,
                'currency' => 'RUB',
                'total_quantity' => 4,
                'total_amount' => '0.00',
                'reference_type' => 'client_order',
                'reference_id' => 8,
                'finalized_at' => '2023-10-06 15:17:10',
                'created_at' => '2023-10-06 15:17:01',
                'updated_at' => '2023-10-06 15:17:10',
                'deleted_at' => NULL,
                'comment' => NULL,
            ),
            
            array (
                'id' => 18,
                'provider_id' => 2,
                'barcode' => '2023 10 06 000002',
                'user_id' => 1,
                'warehouse_id' => 1,
                'currency' => 'RUB',
                'total_quantity' => 7,
                'total_amount' => '0.00',
                'reference_type' => 'client_order',
                'reference_id' => 7,
                'finalized_at' => '2023-10-06 15:18:38',
                'created_at' => '2023-10-06 15:18:31',
                'updated_at' => '2023-10-06 15:18:38',
                'deleted_at' => NULL,
                'comment' => NULL,
            ),
            
            array (
                'id' => 19,
                'provider_id' => 2,
                'barcode' => '2023 10 06 000002',
                'user_id' => 1,
                'warehouse_id' => 1,
                'currency' => 'RUB',
                'total_quantity' => 1,
                'total_amount' => '0.00',
                'reference_type' => 'client_order',
                'reference_id' => 9,
                'finalized_at' => '2023-10-06 16:38:17',
                'created_at' => '2023-10-06 16:38:09',
                'updated_at' => '2023-10-06 16:38:17',
                'deleted_at' => NULL,
                'comment' => NULL,
            ),
            
            array (
                'id' => 20,
                'provider_id' => 2,
                'barcode' => '2023 10 07 000002',
                'user_id' => 1,
                'warehouse_id' => 1,
                'currency' => 'RUB',
                'total_quantity' => 1,
                'total_amount' => '0.00',
                'reference_type' => 'client_order',
                'reference_id' => 10,
                'finalized_at' => '2023-10-07 12:56:55',
                'created_at' => '2023-10-07 12:56:48',
                'updated_at' => '2023-10-07 12:56:55',
                'deleted_at' => NULL,
                'comment' => NULL,
            ),
            
            array (
                'id' => 21,
                'provider_id' => 2,
                'barcode' => '2023 10 08 000002',
                'user_id' => 1,
                'warehouse_id' => 1,
                'currency' => 'RUB',
                'total_quantity' => 2,
                'total_amount' => '0.00',
                'reference_type' => 'client_order',
                'reference_id' => 11,
                'finalized_at' => '2023-10-08 15:31:14',
                'created_at' => '2023-10-08 15:31:06',
                'updated_at' => '2023-10-08 15:31:14',
                'deleted_at' => NULL,
                'comment' => NULL,
            ),
            
            array (
                'id' => 22,
                'provider_id' => 4,
                'barcode' => '2023 10 10 000004',
                'user_id' => 1,
                'warehouse_id' => 1,
                'currency' => 'RUB',
                'total_quantity' => 1,
                'total_amount' => '0.00',
                'reference_type' => 'client_order',
                'reference_id' => 12,
                'finalized_at' => '2023-10-10 15:59:37',
                'created_at' => '2023-10-10 15:58:00',
                'updated_at' => '2023-10-10 15:59:37',
                'deleted_at' => NULL,
                'comment' => NULL,
            ),
            
            array (
                'id' => 23,
                'provider_id' => 2,
                'barcode' => '2023 10 12 000002',
                'user_id' => 1,
                'warehouse_id' => 1,
                'currency' => 'RUB',
                'total_quantity' => 1,
                'total_amount' => '0.00',
                'reference_type' => 'client_order',
                'reference_id' => 13,
                'finalized_at' => '2023-10-12 16:18:03',
                'created_at' => '2023-10-12 16:17:57',
                'updated_at' => '2023-10-12 16:18:03',
                'deleted_at' => NULL,
                'comment' => NULL,
            ),
            
            array (
                'id' => 24,
                'provider_id' => 2,
                'barcode' => '2023 10 14 000001',
                'user_id' => 1,
                'warehouse_id' => 1,
                'currency' => 'RUB',
                'total_quantity' => 4,
                'total_amount' => '0.00',
                'reference_type' => 'client_order',
                'reference_id' => 14,
                'finalized_at' => '2023-10-14 10:26:37',
                'created_at' => '2023-10-14 10:26:23',
                'updated_at' => '2023-10-14 10:26:37',
                'deleted_at' => NULL,
                'comment' => NULL,
            ),
            
            array (
                'id' => 25,
                'provider_id' => 2,
                'barcode' => '2023 10 17 000002',
                'user_id' => 1,
                'warehouse_id' => 1,
                'currency' => 'RUB',
                'total_quantity' => 1,
                'total_amount' => '0.00',
                'reference_type' => 'client_order',
                'reference_id' => 15,
                'finalized_at' => '2023-10-17 16:36:26',
                'created_at' => '2023-10-17 12:58:42',
                'updated_at' => '2023-10-17 16:36:26',
                'deleted_at' => NULL,
                'comment' => NULL,
            ),
            
            array (
                'id' => 26,
                'provider_id' => 5,
                'barcode' => '2023 10 17 000005',
                'user_id' => 1,
                'warehouse_id' => 1,
                'currency' => 'RUB',
                'total_quantity' => 3,
                'total_amount' => '0.00',
                'reference_type' => 'client_order',
                'reference_id' => 15,
                'finalized_at' => '2023-10-17 15:20:42',
                'created_at' => '2023-10-17 15:20:20',
                'updated_at' => '2023-10-17 15:20:42',
                'deleted_at' => NULL,
                'comment' => NULL,
            ),
            
            array (
                'id' => 27,
                'provider_id' => 5,
                'barcode' => '2023 10 18 000005',
                'user_id' => 1,
                'warehouse_id' => 1,
                'currency' => 'RUB',
                'total_quantity' => 1,
                'total_amount' => '0.00',
                'reference_type' => 'client_order',
                'reference_id' => 16,
                'finalized_at' => '2023-10-18 12:28:22',
                'created_at' => '2023-10-18 12:28:13',
                'updated_at' => '2023-10-18 12:28:22',
                'deleted_at' => NULL,
                'comment' => NULL,
            ),
            
            array (
                'id' => 28,
                'provider_id' => 5,
                'barcode' => '2023 10 18 000005',
                'user_id' => 1,
                'warehouse_id' => 1,
                'currency' => 'RUB',
                'total_quantity' => 2,
                'total_amount' => '0.00',
                'reference_type' => 'client_order',
                'reference_id' => 17,
                'finalized_at' => '2023-10-18 12:31:53',
                'created_at' => '2023-10-18 12:31:08',
                'updated_at' => '2023-10-18 12:31:53',
                'deleted_at' => NULL,
                'comment' => NULL,
            ),
            
            array (
                'id' => 29,
                'provider_id' => 4,
                'barcode' => '2023 10 18 000004',
                'user_id' => 1,
                'warehouse_id' => 1,
                'currency' => 'RUB',
                'total_quantity' => 4,
                'total_amount' => '0.00',
                'reference_type' => 'client_order',
                'reference_id' => 17,
                'finalized_at' => '2023-10-18 12:32:40',
                'created_at' => '2023-10-18 12:32:20',
                'updated_at' => '2023-10-18 12:32:40',
                'deleted_at' => NULL,
                'comment' => NULL,
            ),
            
            array (
                'id' => 31,
                'provider_id' => 2,
                'barcode' => '2023 10 20 000002',
                'user_id' => 1,
                'warehouse_id' => 1,
                'currency' => 'RUB',
                'total_quantity' => 24,
                'total_amount' => '0.00',
                'reference_type' => 'client_order',
                'reference_id' => 18,
                'finalized_at' => '2023-10-20 14:56:40',
                'created_at' => '2023-10-20 14:56:34',
                'updated_at' => '2023-10-20 14:56:40',
                'deleted_at' => NULL,
                'comment' => NULL,
            ),
            
            array (
                'id' => 32,
                'provider_id' => 2,
                'barcode' => '2023 10 22 000002',
                'user_id' => 1,
                'warehouse_id' => 1,
                'currency' => 'RUB',
                'total_quantity' => 2,
                'total_amount' => '0.00',
                'reference_type' => 'client_order',
                'reference_id' => 19,
                'finalized_at' => '2023-10-22 07:46:02',
                'created_at' => '2023-10-22 07:45:54',
                'updated_at' => '2023-10-22 07:46:02',
                'deleted_at' => NULL,
                'comment' => NULL,
            ),
            
            array (
                'id' => 33,
                'provider_id' => 2,
                'barcode' => '2023 10 23 000002',
                'user_id' => 1,
                'warehouse_id' => 1,
                'currency' => 'RUB',
                'total_quantity' => 2,
                'total_amount' => '0.00',
                'reference_type' => 'client_order',
                'reference_id' => 20,
                'finalized_at' => '2023-10-23 09:59:50',
                'created_at' => '2023-10-23 09:59:44',
                'updated_at' => '2023-10-23 09:59:50',
                'deleted_at' => NULL,
                'comment' => NULL,
            ),
            
            array (
                'id' => 34,
                'provider_id' => 5,
                'barcode' => '2023 10 23 000005',
                'user_id' => 1,
                'warehouse_id' => 1,
                'currency' => 'RUB',
                'total_quantity' => 2,
                'total_amount' => '0.00',
                'reference_type' => 'client_order',
                'reference_id' => 21,
                'finalized_at' => '2023-10-23 12:51:12',
                'created_at' => '2023-10-23 12:50:59',
                'updated_at' => '2023-10-23 12:51:12',
                'deleted_at' => NULL,
                'comment' => NULL,
            ),
            
            array (
                'id' => 35,
                'provider_id' => 7,
                'barcode' => '2023 10 23 000007',
                'user_id' => 1,
                'warehouse_id' => 1,
                'currency' => 'RUB',
                'total_quantity' => 1,
                'total_amount' => '0.00',
                'reference_type' => 'client_order',
                'reference_id' => 21,
                'finalized_at' => '2023-10-23 13:06:10',
                'created_at' => '2023-10-23 13:04:46',
                'updated_at' => '2023-10-23 13:06:10',
                'deleted_at' => NULL,
                'comment' => NULL,
            ),
            
            array (
                'id' => 36,
                'provider_id' => 2,
                'barcode' => '2023 10 24 000002',
                'user_id' => 1,
                'warehouse_id' => 1,
                'currency' => 'RUB',
                'total_quantity' => 1,
                'total_amount' => '0.00',
                'reference_type' => 'client_order',
                'reference_id' => 22,
                'finalized_at' => '2023-10-24 05:33:22',
                'created_at' => '2023-10-24 05:33:17',
                'updated_at' => '2023-10-24 05:33:22',
                'deleted_at' => NULL,
                'comment' => NULL,
            ),
            
            array (
                'id' => 37,
                'provider_id' => 5,
                'barcode' => '2023 10 25 000005',
                'user_id' => 1,
                'warehouse_id' => 1,
                'currency' => 'RUB',
                'total_quantity' => 8,
                'total_amount' => '0.00',
                'reference_type' => 'client_order',
                'reference_id' => 23,
                'finalized_at' => '2023-10-25 10:28:21',
                'created_at' => '2023-10-25 05:08:04',
                'updated_at' => '2023-10-25 10:28:21',
                'deleted_at' => NULL,
                'comment' => NULL,
            ),
            
            array (
                'id' => 38,
                'provider_id' => 2,
                'barcode' => '2023 10 26 000002',
                'user_id' => 1,
                'warehouse_id' => 1,
                'currency' => 'RUB',
                'total_quantity' => 1,
                'total_amount' => '0.00',
                'reference_type' => 'client_order',
                'reference_id' => 24,
                'finalized_at' => '2023-10-26 16:25:10',
                'created_at' => '2023-10-26 16:25:03',
                'updated_at' => '2023-10-26 16:25:10',
                'deleted_at' => NULL,
                'comment' => NULL,
            ),
            
            array (
                'id' => 39,
                'provider_id' => 2,
                'barcode' => '2023 10 26 000002',
                'user_id' => 1,
                'warehouse_id' => 1,
                'currency' => 'RUB',
                'total_quantity' => 5,
                'total_amount' => '0.00',
                'reference_type' => 'client_order',
                'reference_id' => 25,
                'finalized_at' => '2023-10-26 16:48:51',
                'created_at' => '2023-10-26 16:48:24',
                'updated_at' => '2023-10-26 16:48:51',
                'deleted_at' => NULL,
                'comment' => NULL,
            ),
            
            array (
                'id' => 40,
                'provider_id' => 2,
                'barcode' => '2023 10 26 000002',
                'user_id' => 1,
                'warehouse_id' => 1,
                'currency' => 'RUB',
                'total_quantity' => 2,
                'total_amount' => '0.00',
                'reference_type' => 'client_order',
                'reference_id' => 26,
                'finalized_at' => '2023-10-28 17:04:01',
                'created_at' => '2023-10-26 16:50:19',
                'updated_at' => '2023-10-28 17:04:01',
                'deleted_at' => NULL,
                'comment' => NULL,
            ),
            
            array (
                'id' => 41,
                'provider_id' => 2,
                'barcode' => '2023 10 26 000002',
                'user_id' => 1,
                'warehouse_id' => 1,
                'currency' => 'RUB',
                'total_quantity' => 15,
                'total_amount' => '0.00',
                'reference_type' => NULL,
                'reference_id' => NULL,
                'finalized_at' => '2023-10-28 15:23:53',
                'created_at' => '2023-10-26 16:55:33',
                'updated_at' => '2023-10-28 15:23:53',
                'deleted_at' => NULL,
                'comment' => NULL,
            ),
            
            array (
                'id' => 42,
                'provider_id' => 2,
                'barcode' => '2023 10 27 000002',
                'user_id' => 1,
                'warehouse_id' => 1,
                'currency' => 'RUB',
                'total_quantity' => 12,
                'total_amount' => '0.00',
                'reference_type' => 'client_order',
                'reference_id' => 27,
                'finalized_at' => '2023-10-27 12:39:27',
                'created_at' => '2023-10-27 12:39:21',
                'updated_at' => '2023-10-27 12:39:27',
                'deleted_at' => NULL,
                'comment' => NULL,
            ),
            
            array (
                'id' => 43,
                'provider_id' => 5,
                'barcode' => '2023 10 29 000005',
                'user_id' => 1,
                'warehouse_id' => 1,
                'currency' => 'RUB',
                'total_quantity' => 2,
                'total_amount' => '0.00',
                'reference_type' => 'client_order',
                'reference_id' => 28,
                'finalized_at' => '2023-10-29 19:30:49',
                'created_at' => '2023-10-29 19:28:46',
                'updated_at' => '2023-10-29 19:30:49',
                'deleted_at' => NULL,
                'comment' => NULL,
            ),
            
            array (
                'id' => 44,
                'provider_id' => 2,
                'barcode' => '2023 11 06 000002',
                'user_id' => 1,
                'warehouse_id' => 1,
                'currency' => 'RUB',
                'total_quantity' => 2,
                'total_amount' => '2985.00',
                'reference_type' => 'client_order',
                'reference_id' => 31,
                'finalized_at' => '2023-11-06 10:11:55',
                'created_at' => '2023-11-06 10:10:19',
                'updated_at' => '2023-11-06 10:11:55',
                'deleted_at' => NULL,
                'comment' => NULL,
            ),
            
            array (
                'id' => 45,
                'provider_id' => 2,
                'barcode' => '2023 11 08 000002',
                'user_id' => 1,
                'warehouse_id' => 1,
                'currency' => 'RUB',
                'total_quantity' => 1,
                'total_amount' => '0.00',
                'reference_type' => 'client_order',
                'reference_id' => 33,
                'finalized_at' => '2023-11-08 09:33:11',
                'created_at' => '2023-11-08 09:33:03',
                'updated_at' => '2023-11-08 09:33:11',
                'deleted_at' => NULL,
                'comment' => NULL,
            ),
            
            array (
                'id' => 46,
                'provider_id' => 5,
                'barcode' => '2023 11 09 000005',
                'user_id' => 1,
                'warehouse_id' => 1,
                'currency' => 'RUB',
                'total_quantity' => 1,
                'total_amount' => '0.00',
                'reference_type' => 'client_order',
                'reference_id' => 34,
                'finalized_at' => '2023-11-09 10:30:33',
                'created_at' => '2023-11-09 10:30:25',
                'updated_at' => '2023-11-09 10:30:33',
                'deleted_at' => NULL,
                'comment' => NULL,
            ),
            
            array (
                'id' => 47,
                'provider_id' => 5,
                'barcode' => '2023 11 10 000005',
                'user_id' => 1,
                'warehouse_id' => 1,
                'currency' => 'RUB',
                'total_quantity' => 16,
                'total_amount' => '0.00',
                'reference_type' => 'client_order',
                'reference_id' => 32,
                'finalized_at' => '2023-11-10 14:16:53',
                'created_at' => '2023-11-10 14:16:07',
                'updated_at' => '2023-11-10 14:16:53',
                'deleted_at' => NULL,
                'comment' => NULL,
            ),
            
            array (
                'id' => 48,
                'provider_id' => 8,
                'barcode' => '2023 11 10 000008',
                'user_id' => 1,
                'warehouse_id' => 1,
                'currency' => 'RUB',
                'total_quantity' => 2,
                'total_amount' => '0.00',
                'reference_type' => 'client_order',
                'reference_id' => 32,
                'finalized_at' => '2023-11-14 07:11:50',
                'created_at' => '2023-11-10 14:17:08',
                'updated_at' => '2023-11-14 07:11:50',
                'deleted_at' => NULL,
                'comment' => NULL,
            ),
            
            array (
                'id' => 49,
                'provider_id' => 2,
                'barcode' => '2023 11 10 000002',
                'user_id' => 1,
                'warehouse_id' => 1,
                'currency' => 'RUB',
                'total_quantity' => 5,
                'total_amount' => '0.00',
                'reference_type' => 'client_order',
                'reference_id' => 32,
                'finalized_at' => '2023-11-10 14:22:22',
                'created_at' => '2023-11-10 14:18:00',
                'updated_at' => '2023-11-10 14:22:22',
                'deleted_at' => NULL,
                'comment' => NULL,
            ),
            
            array (
                'id' => 50,
                'provider_id' => 2,
                'barcode' => '2023 11 13 000002',
                'user_id' => 1,
                'warehouse_id' => 1,
                'currency' => 'RUB',
                'total_quantity' => 2,
                'total_amount' => '0.00',
                'reference_type' => 'client_order',
                'reference_id' => 41,
                'finalized_at' => '2023-11-13 20:11:38',
                'created_at' => '2023-11-13 20:11:25',
                'updated_at' => '2023-11-13 20:11:38',
                'deleted_at' => NULL,
                'comment' => NULL,
            ),
            
            array (
                'id' => 51,
                'provider_id' => 5,
                'barcode' => '2023 11 13 000005',
                'user_id' => 1,
                'warehouse_id' => 1,
                'currency' => 'RUB',
                'total_quantity' => 1,
                'total_amount' => '0.00',
                'reference_type' => 'client_order',
                'reference_id' => 42,
                'finalized_at' => '2023-11-13 20:12:37',
                'created_at' => '2023-11-13 20:12:28',
                'updated_at' => '2023-11-13 20:12:37',
                'deleted_at' => NULL,
                'comment' => NULL,
            ),
            
            array (
                'id' => 52,
                'provider_id' => 8,
                'barcode' => '2023 11 14 000008',
                'user_id' => 1,
                'warehouse_id' => 1,
                'currency' => 'RUB',
                'total_quantity' => 7,
                'total_amount' => '16350.00',
                'reference_type' => NULL,
                'reference_id' => NULL,
                'finalized_at' => '2023-11-14 10:28:58',
                'created_at' => '2023-11-14 10:21:28',
                'updated_at' => '2023-11-14 10:28:58',
                'deleted_at' => NULL,
                'comment' => NULL,
            ),
            
            array (
                'id' => 53,
                'provider_id' => 2,
                'barcode' => '2023 11 14 000002',
                'user_id' => 1,
                'warehouse_id' => 1,
                'currency' => 'RUB',
                'total_quantity' => 2,
                'total_amount' => '0.00',
                'reference_type' => 'client_order',
                'reference_id' => 36,
                'finalized_at' => '2023-11-14 14:40:32',
                'created_at' => '2023-11-14 14:39:48',
                'updated_at' => '2023-11-14 14:40:32',
                'deleted_at' => NULL,
                'comment' => NULL,
            ),
            
            array (
                'id' => 54,
                'provider_id' => 2,
                'barcode' => '2023 11 14 000002',
                'user_id' => 1,
                'warehouse_id' => 1,
                'currency' => 'RUB',
                'total_quantity' => 5,
                'total_amount' => '0.00',
                'reference_type' => 'client_order',
                'reference_id' => 35,
                'finalized_at' => '2023-11-14 15:08:20',
                'created_at' => '2023-11-14 15:07:52',
                'updated_at' => '2023-11-14 15:08:20',
                'deleted_at' => NULL,
                'comment' => NULL,
            ),
            
            array (
                'id' => 55,
                'provider_id' => 5,
                'barcode' => '2023 11 15 000005',
                'user_id' => 1,
                'warehouse_id' => 1,
                'currency' => 'RUB',
                'total_quantity' => 2,
                'total_amount' => '0.00',
                'reference_type' => 'client_order',
                'reference_id' => 43,
                'finalized_at' => '2023-11-15 11:25:18',
                'created_at' => '2023-11-15 11:25:06',
                'updated_at' => '2023-11-15 11:25:18',
                'deleted_at' => NULL,
                'comment' => NULL,
            ),
            
            array (
                'id' => 56,
                'provider_id' => 2,
                'barcode' => '2023 11 15 000002',
                'user_id' => 1,
                'warehouse_id' => 1,
                'currency' => 'RUB',
                'total_quantity' => 10,
                'total_amount' => '0.00',
                'reference_type' => 'client_order',
                'reference_id' => 44,
                'finalized_at' => '2023-11-15 14:47:14',
                'created_at' => '2023-11-15 14:47:02',
                'updated_at' => '2023-11-15 14:47:14',
                'deleted_at' => NULL,
                'comment' => NULL,
            ),
            
            array (
                'id' => 57,
                'provider_id' => 2,
                'barcode' => '2023 11 15 000002',
                'user_id' => 1,
                'warehouse_id' => 1,
                'currency' => 'RUB',
                'total_quantity' => 2,
                'total_amount' => '0.00',
                'reference_type' => 'client_order',
                'reference_id' => 37,
                'finalized_at' => '2023-11-15 16:18:00',
                'created_at' => '2023-11-15 16:17:21',
                'updated_at' => '2023-11-15 16:18:00',
                'deleted_at' => NULL,
                'comment' => NULL,
            ),
            
            array (
                'id' => 58,
                'provider_id' => 2,
                'barcode' => '2023 11 16 000002',
                'user_id' => 1,
                'warehouse_id' => 1,
                'currency' => 'RUB',
                'total_quantity' => 4,
                'total_amount' => '0.00',
                'reference_type' => 'client_order',
                'reference_id' => 45,
                'finalized_at' => '2023-11-16 08:11:43',
                'created_at' => '2023-11-16 08:11:34',
                'updated_at' => '2023-11-16 08:11:43',
                'deleted_at' => NULL,
                'comment' => NULL,
            ),
            
            array (
                'id' => 59,
                'provider_id' => 2,
                'barcode' => '2023 11 16 000002',
                'user_id' => 1,
                'warehouse_id' => 1,
                'currency' => 'RUB',
                'total_quantity' => 5,
                'total_amount' => '0.00',
                'reference_type' => 'client_order',
                'reference_id' => 46,
                'finalized_at' => '2023-11-16 08:15:15',
                'created_at' => '2023-11-16 08:15:03',
                'updated_at' => '2023-11-16 08:15:15',
                'deleted_at' => NULL,
                'comment' => NULL,
            ),
            
            array (
                'id' => 60,
                'provider_id' => 2,
                'barcode' => '2023 11 17 000002',
                'user_id' => 1,
                'warehouse_id' => 1,
                'currency' => 'RUB',
                'total_quantity' => 1,
                'total_amount' => '0.00',
                'reference_type' => 'client_order',
                'reference_id' => 47,
                'finalized_at' => '2023-11-17 05:47:15',
                'created_at' => '2023-11-17 05:47:06',
                'updated_at' => '2023-11-17 05:47:15',
                'deleted_at' => NULL,
                'comment' => NULL,
            ),
            
            array (
                'id' => 61,
                'provider_id' => 2,
                'barcode' => '2023 11 21 000002',
                'user_id' => 1,
                'warehouse_id' => 1,
                'currency' => 'RUB',
                'total_quantity' => 2,
                'total_amount' => '902.00',
                'reference_type' => NULL,
                'reference_id' => NULL,
                'finalized_at' => '2023-11-21 06:01:40',
                'created_at' => '2023-11-21 06:00:21',
                'updated_at' => '2023-11-21 06:01:40',
                'deleted_at' => NULL,
                'comment' => NULL,
            ),
            
            array (
                'id' => 62,
                'provider_id' => 2,
                'barcode' => '2023 11 21 000002',
                'user_id' => 1,
                'warehouse_id' => 1,
                'currency' => 'RUB',
                'total_quantity' => 1,
                'total_amount' => '0.00',
                'reference_type' => 'client_order',
                'reference_id' => 49,
                'finalized_at' => '2023-11-21 17:15:19',
                'created_at' => '2023-11-21 16:50:31',
                'updated_at' => '2023-11-21 17:15:19',
                'deleted_at' => NULL,
                'comment' => NULL,
            ),
            
            array (
                'id' => 63,
                'provider_id' => 2,
                'barcode' => '2023 11 22 000002',
                'user_id' => 1,
                'warehouse_id' => 1,
                'currency' => 'RUB',
                'total_quantity' => 2,
                'total_amount' => '0.00',
                'reference_type' => 'client_order',
                'reference_id' => 50,
                'finalized_at' => '2023-11-22 11:36:22',
                'created_at' => '2023-11-22 11:35:28',
                'updated_at' => '2023-11-22 11:36:22',
                'deleted_at' => NULL,
                'comment' => NULL,
            ),
            
            array (
                'id' => 64,
                'provider_id' => 5,
                'barcode' => '2023 11 22 000005',
                'user_id' => 1,
                'warehouse_id' => 1,
                'currency' => 'RUB',
                'total_quantity' => 1,
                'total_amount' => '0.00',
                'reference_type' => 'client_order',
                'reference_id' => 50,
                'finalized_at' => '2023-11-22 11:37:03',
                'created_at' => '2023-11-22 11:35:45',
                'updated_at' => '2023-11-22 11:37:03',
                'deleted_at' => NULL,
                'comment' => NULL,
            ),
            
            array (
                'id' => 65,
                'provider_id' => 2,
                'barcode' => '2023 11 23 000002',
                'user_id' => 1,
                'warehouse_id' => 1,
                'currency' => 'RUB',
                'total_quantity' => 1,
                'total_amount' => '0.00',
                'reference_type' => 'client_order',
                'reference_id' => 51,
                'finalized_at' => '2023-11-23 13:41:37',
                'created_at' => '2023-11-23 13:41:02',
                'updated_at' => '2023-11-23 13:41:37',
                'deleted_at' => NULL,
                'comment' => NULL,
            ),
            
            array (
                'id' => 66,
                'provider_id' => 8,
                'barcode' => '2023 11 23 000008',
                'user_id' => 1,
                'warehouse_id' => 1,
                'currency' => 'RUB',
                'total_quantity' => 2,
                'total_amount' => '0.00',
                'reference_type' => 'client_order',
                'reference_id' => 51,
                'finalized_at' => '2023-11-23 13:42:28',
                'created_at' => '2023-11-23 13:41:54',
                'updated_at' => '2023-11-23 13:42:28',
                'deleted_at' => NULL,
                'comment' => NULL,
            ),
            
            array (
                'id' => 67,
                'provider_id' => 2,
                'barcode' => '2023 11 23 000002',
                'user_id' => 1,
                'warehouse_id' => 1,
                'currency' => 'RUB',
                'total_quantity' => 3,
                'total_amount' => '0.00',
                'reference_type' => 'client_order',
                'reference_id' => 52,
                'finalized_at' => '2023-11-23 13:46:00',
                'created_at' => '2023-11-23 13:45:41',
                'updated_at' => '2023-11-23 13:46:00',
                'deleted_at' => NULL,
                'comment' => NULL,
            ),
            
            array (
                'id' => 69,
                'provider_id' => 2,
                'barcode' => '2023 11 26 000002',
                'user_id' => 1,
                'warehouse_id' => 1,
                'currency' => 'RUB',
                'total_quantity' => 10,
                'total_amount' => '0.00',
                'reference_type' => 'client_order',
                'reference_id' => 54,
                'finalized_at' => '2023-11-26 07:39:51',
                'created_at' => '2023-11-26 07:39:42',
                'updated_at' => '2023-11-26 07:39:51',
                'deleted_at' => NULL,
                'comment' => NULL,
            ),
            
            array (
                'id' => 70,
                'provider_id' => 2,
                'barcode' => '2023 11 27 000002',
                'user_id' => 1,
                'warehouse_id' => 1,
                'currency' => 'RUB',
                'total_quantity' => 6,
                'total_amount' => '0.00',
                'reference_type' => 'client_order',
                'reference_id' => 55,
                'finalized_at' => '2023-11-27 11:33:35',
                'created_at' => '2023-11-27 11:33:26',
                'updated_at' => '2023-11-27 11:33:35',
                'deleted_at' => NULL,
                'comment' => NULL,
            ),
            
            array (
                'id' => 71,
                'provider_id' => 2,
                'barcode' => '2023 11 28 000002',
                'user_id' => 1,
                'warehouse_id' => 1,
                'currency' => 'RUB',
                'total_quantity' => 3,
                'total_amount' => '0.00',
                'reference_type' => 'client_order',
                'reference_id' => 56,
                'finalized_at' => '2023-11-28 05:46:24',
                'created_at' => '2023-11-28 05:46:14',
                'updated_at' => '2023-11-28 05:46:24',
                'deleted_at' => NULL,
                'comment' => NULL,
            ),
            
            array (
                'id' => 72,
                'provider_id' => 8,
                'barcode' => '2023 11 29 000008',
                'user_id' => 1,
                'warehouse_id' => 1,
                'currency' => 'RUB',
                'total_quantity' => 1,
                'total_amount' => '0.00',
                'reference_type' => 'client_order',
                'reference_id' => 57,
                'finalized_at' => '2023-11-29 10:00:05',
                'created_at' => '2023-11-29 09:59:50',
                'updated_at' => '2023-11-29 10:00:05',
                'deleted_at' => NULL,
                'comment' => NULL,
            ),
            
            array (
                'id' => 73,
                'provider_id' => 2,
                'barcode' => '2023 11 29 000002',
                'user_id' => 1,
                'warehouse_id' => 1,
                'currency' => 'RUB',
                'total_quantity' => 1,
                'total_amount' => '0.00',
                'reference_type' => 'client_order',
                'reference_id' => 57,
                'finalized_at' => '2023-11-29 10:00:33',
                'created_at' => '2023-11-29 10:00:14',
                'updated_at' => '2023-11-29 10:00:33',
                'deleted_at' => NULL,
                'comment' => NULL,
            ),
            
            array (
                'id' => 74,
                'provider_id' => 2,
                'barcode' => '2023 11 29 000002',
                'user_id' => 1,
                'warehouse_id' => 1,
                'currency' => 'RUB',
                'total_quantity' => 2,
                'total_amount' => '0.00',
                'reference_type' => 'client_order',
                'reference_id' => 58,
                'finalized_at' => '2023-11-29 13:13:17',
                'created_at' => '2023-11-29 13:13:07',
                'updated_at' => '2023-11-29 13:13:17',
                'deleted_at' => NULL,
                'comment' => NULL,
            ),
            
            array (
                'id' => 75,
                'provider_id' => 3,
                'barcode' => '2023 12 02 000003',
                'user_id' => 1,
                'warehouse_id' => 1,
                'currency' => 'RUB',
                'total_quantity' => 2,
                'total_amount' => '2200.00',
                'reference_type' => 'client_order',
                'reference_id' => 59,
                'finalized_at' => '2023-12-02 11:44:14',
                'created_at' => '2023-12-02 11:43:56',
                'updated_at' => '2023-12-02 11:44:14',
                'deleted_at' => NULL,
                'comment' => NULL,
            ),
            
            array (
                'id' => 76,
                'provider_id' => 2,
                'barcode' => '2023 12 05 000002',
                'user_id' => 1,
                'warehouse_id' => 1,
                'currency' => 'RUB',
                'total_quantity' => 4,
                'total_amount' => '3095.00',
                'reference_type' => NULL,
                'reference_id' => NULL,
                'finalized_at' => '2023-12-05 11:43:43',
                'created_at' => '2023-12-05 11:34:55',
                'updated_at' => '2023-12-05 11:43:43',
                'deleted_at' => NULL,
                'comment' => NULL,
            ),
            
            array (
                'id' => 77,
                'provider_id' => 2,
                'barcode' => '2023 12 06 000002',
                'user_id' => 1,
                'warehouse_id' => 1,
                'currency' => 'RUB',
                'total_quantity' => 1,
                'total_amount' => '3975.00',
                'reference_type' => 'client_order',
                'reference_id' => 60,
                'finalized_at' => '2023-12-06 11:07:21',
                'created_at' => '2023-12-06 11:05:31',
                'updated_at' => '2023-12-06 11:07:21',
                'deleted_at' => NULL,
                'comment' => NULL,
            ),
            
            array (
                'id' => 78,
                'provider_id' => 2,
                'barcode' => '2023 12 07 000002',
                'user_id' => 1,
                'warehouse_id' => 1,
                'currency' => 'RUB',
                'total_quantity' => 1,
                'total_amount' => '0.00',
                'reference_type' => 'client_order',
                'reference_id' => 61,
                'finalized_at' => '2023-12-07 10:55:32',
                'created_at' => '2023-12-07 10:55:15',
                'updated_at' => '2023-12-07 10:55:32',
                'deleted_at' => NULL,
                'comment' => NULL,
            ),
            
            array (
                'id' => 80,
                'provider_id' => 2,
                'barcode' => '2023 12 09 000002',
                'user_id' => 1,
                'warehouse_id' => 1,
                'currency' => 'RUB',
                'total_quantity' => 6,
                'total_amount' => '0.00',
                'reference_type' => 'client_order',
                'reference_id' => 62,
                'finalized_at' => '2023-12-09 16:26:05',
                'created_at' => '2023-12-09 16:25:50',
                'updated_at' => '2023-12-09 16:26:05',
                'deleted_at' => NULL,
                'comment' => NULL,
            ),
            
            array (
                'id' => 81,
                'provider_id' => 2,
                'barcode' => '2023 12 12 000002',
                'user_id' => 1,
                'warehouse_id' => 1,
                'currency' => 'RUB',
                'total_quantity' => 1,
                'total_amount' => '0.00',
                'reference_type' => 'client_order',
                'reference_id' => 63,
                'finalized_at' => '2023-12-12 19:17:26',
                'created_at' => '2023-12-12 19:17:13',
                'updated_at' => '2023-12-12 19:17:26',
                'deleted_at' => NULL,
                'comment' => NULL,
            ),
            
            array (
                'id' => 83,
                'provider_id' => 2,
                'barcode' => '2023 12 26 000002',
                'user_id' => 1,
                'warehouse_id' => 1,
                'currency' => 'RUB',
                'total_quantity' => 3,
                'total_amount' => '0.00',
                'reference_type' => 'client_order',
                'reference_id' => 65,
                'finalized_at' => '2023-12-26 17:24:28',
                'created_at' => '2023-12-26 17:23:12',
                'updated_at' => '2023-12-26 17:24:28',
                'deleted_at' => NULL,
                'comment' => NULL,
            ),
            
            array (
                'id' => 84,
                'provider_id' => 5,
                'barcode' => '2023 12 26 000005',
                'user_id' => 1,
                'warehouse_id' => 1,
                'currency' => 'RUB',
                'total_quantity' => 2,
                'total_amount' => '0.00',
                'reference_type' => 'client_order',
                'reference_id' => 65,
                'finalized_at' => '2023-12-26 17:24:43',
                'created_at' => '2023-12-26 17:23:25',
                'updated_at' => '2023-12-26 17:24:43',
                'deleted_at' => NULL,
                'comment' => NULL,
            ),
            
            array (
                'id' => 85,
                'provider_id' => 2,
                'barcode' => '2023 12 27 000002',
                'user_id' => 1,
                'warehouse_id' => 1,
                'currency' => 'RUB',
                'total_quantity' => 2,
                'total_amount' => '0.00',
                'reference_type' => 'client_order',
                'reference_id' => 66,
                'finalized_at' => '2023-12-27 11:49:10',
                'created_at' => '2023-12-27 11:48:48',
                'updated_at' => '2023-12-27 11:49:10',
                'deleted_at' => NULL,
                'comment' => NULL,
            ),
            
            array (
                'id' => 86,
                'provider_id' => 2,
                'barcode' => '2024 01 10 000002',
                'user_id' => 1,
                'warehouse_id' => 1,
                'currency' => 'RUB',
                'total_quantity' => 1,
                'total_amount' => '5960.00',
                'reference_type' => 'client_order',
                'reference_id' => 67,
                'finalized_at' => '2024-01-10 13:02:20',
                'created_at' => '2024-01-10 13:01:57',
                'updated_at' => '2024-01-10 13:02:20',
                'deleted_at' => NULL,
                'comment' => NULL,
            ),
            
            array (
                'id' => 87,
                'provider_id' => 2,
                'barcode' => '2024 01 10 000002',
                'user_id' => 1,
                'warehouse_id' => 2,
                'currency' => 'RUB',
                'total_quantity' => 2,
                'total_amount' => '0.00',
                'reference_type' => 'client_order',
                'reference_id' => 68,
                'finalized_at' => '2024-01-10 19:19:19',
                'created_at' => '2024-01-10 19:19:05',
                'updated_at' => '2024-01-10 19:19:19',
                'deleted_at' => NULL,
                'comment' => NULL,
            ),
            
            array (
                'id' => 88,
                'provider_id' => 2,
                'barcode' => '2024 01 11 000002',
                'user_id' => 1,
                'warehouse_id' => 1,
                'currency' => 'RUB',
                'total_quantity' => 1,
                'total_amount' => '0.00',
                'reference_type' => 'client_order',
                'reference_id' => 69,
                'finalized_at' => '2024-01-11 09:27:44',
                'created_at' => '2024-01-11 09:27:29',
                'updated_at' => '2024-01-11 09:27:44',
                'deleted_at' => NULL,
                'comment' => NULL,
            ),
            
            array (
                'id' => 90,
                'provider_id' => 2,
                'barcode' => '2024 01 11 000002',
                'user_id' => 1,
                'warehouse_id' => 1,
                'currency' => 'RUB',
                'total_quantity' => 1,
                'total_amount' => '0.00',
                'reference_type' => 'client_order',
                'reference_id' => 70,
                'finalized_at' => '2024-01-11 14:05:09',
                'created_at' => '2024-01-11 14:04:56',
                'updated_at' => '2024-01-11 14:05:09',
                'deleted_at' => NULL,
                'comment' => NULL,
            ),
            
            array (
                'id' => 91,
                'provider_id' => 2,
                'barcode' => '2024 01 17 000002',
                'user_id' => 1,
                'warehouse_id' => 1,
                'currency' => 'RUB',
                'total_quantity' => 5,
                'total_amount' => '0.00',
                'reference_type' => 'client_order',
                'reference_id' => 72,
                'finalized_at' => '2024-01-17 11:16:41',
                'created_at' => '2024-01-17 11:16:27',
                'updated_at' => '2024-01-17 11:16:41',
                'deleted_at' => NULL,
                'comment' => NULL,
            ),
            
            array (
                'id' => 92,
                'provider_id' => 2,
                'barcode' => '2024 01 26 000002',
                'user_id' => 1,
                'warehouse_id' => 1,
                'currency' => 'RUB',
                'total_quantity' => 5,
                'total_amount' => '0.00',
                'reference_type' => 'client_order',
                'reference_id' => 73,
                'finalized_at' => '2024-01-26 16:21:13',
                'created_at' => '2024-01-26 16:20:58',
                'updated_at' => '2024-01-26 16:21:13',
                'deleted_at' => NULL,
                'comment' => NULL,
            ),
            
            array (
                'id' => 93,
                'provider_id' => 5,
                'barcode' => '2024 01 31 000005',
                'user_id' => 1,
                'warehouse_id' => 1,
                'currency' => 'RUB',
                'total_quantity' => 3,
                'total_amount' => '0.00',
                'reference_type' => 'client_order',
                'reference_id' => 76,
                'finalized_at' => '2024-01-31 17:23:02',
                'created_at' => '2024-01-31 17:22:44',
                'updated_at' => '2024-01-31 17:23:02',
                'deleted_at' => NULL,
                'comment' => NULL,
            ),
            
            array (
                'id' => 94,
                'provider_id' => 2,
                'barcode' => '2024 02 01 000002',
                'user_id' => 1,
                'warehouse_id' => 1,
                'currency' => 'RUB',
                'total_quantity' => 1,
                'total_amount' => '0.00',
                'reference_type' => 'client_order',
                'reference_id' => 77,
                'finalized_at' => '2024-02-01 08:07:27',
                'created_at' => '2024-02-01 08:07:00',
                'updated_at' => '2024-02-01 08:07:27',
                'deleted_at' => NULL,
                'comment' => NULL,
            ),
            
            array (
                'id' => 95,
                'provider_id' => 5,
                'barcode' => '2024 02 01 000005',
                'user_id' => 1,
                'warehouse_id' => 1,
                'currency' => 'RUB',
                'total_quantity' => 3,
                'total_amount' => '0.00',
                'reference_type' => 'client_order',
                'reference_id' => 78,
                'finalized_at' => '2024-02-01 11:20:22',
                'created_at' => '2024-02-01 11:20:05',
                'updated_at' => '2024-02-01 11:20:22',
                'deleted_at' => NULL,
                'comment' => NULL,
            ),
            
            array (
                'id' => 97,
                'provider_id' => 2,
                'barcode' => '2024 02 03 000002',
                'user_id' => 1,
                'warehouse_id' => 1,
                'currency' => 'RUB',
                'total_quantity' => 1,
                'total_amount' => '0.00',
                'reference_type' => 'client_order',
                'reference_id' => 80,
                'finalized_at' => '2024-02-03 13:06:59',
                'created_at' => '2024-02-03 13:06:46',
                'updated_at' => '2024-02-03 13:06:59',
                'deleted_at' => NULL,
                'comment' => NULL,
            ),
            
            array (
                'id' => 98,
                'provider_id' => 2,
                'barcode' => '2024 02 08 000002',
                'user_id' => 1,
                'warehouse_id' => 1,
                'currency' => 'RUB',
                'total_quantity' => 3,
                'total_amount' => '513.00',
                'reference_type' => NULL,
                'reference_id' => NULL,
                'finalized_at' => '2024-02-11 10:44:37',
                'created_at' => '2024-02-08 09:20:10',
                'updated_at' => '2024-02-11 10:44:37',
                'deleted_at' => NULL,
                'comment' => NULL,
            ),
            
            array (
                'id' => 99,
                'provider_id' => 5,
                'barcode' => '2024 02 11 000005',
                'user_id' => 1,
                'warehouse_id' => 1,
                'currency' => 'RUB',
                'total_quantity' => 2,
                'total_amount' => '0.00',
                'reference_type' => NULL,
                'reference_id' => NULL,
                'finalized_at' => '2024-02-11 10:45:17',
                'created_at' => '2024-02-11 10:44:02',
                'updated_at' => '2024-02-11 10:45:17',
                'deleted_at' => NULL,
                'comment' => NULL,
            ),
            
            array (
                'id' => 100,
                'provider_id' => 2,
                'barcode' => '2024 02 11 000002',
                'user_id' => 1,
                'warehouse_id' => 1,
                'currency' => 'RUB',
                'total_quantity' => 2,
                'total_amount' => '0.00',
                'reference_type' => NULL,
                'reference_id' => NULL,
                'finalized_at' => '2024-02-11 10:46:12',
                'created_at' => '2024-02-11 10:45:29',
                'updated_at' => '2024-02-11 10:46:12',
                'deleted_at' => NULL,
                'comment' => NULL,
            ),
            
            array (
                'id' => 102,
                'provider_id' => 2,
                'barcode' => '2024 02 12 000002',
                'user_id' => 1,
                'warehouse_id' => 1,
                'currency' => 'RUB',
                'total_quantity' => 2,
                'total_amount' => '0.00',
                'reference_type' => 'client_order',
                'reference_id' => 88,
                'finalized_at' => '2024-02-13 05:10:01',
                'created_at' => '2024-02-12 14:05:43',
                'updated_at' => '2024-02-13 05:10:01',
                'deleted_at' => NULL,
                'comment' => NULL,
            ),
            
            array (
                'id' => 103,
                'provider_id' => 8,
                'barcode' => '2024 02 12 000008',
                'user_id' => 1,
                'warehouse_id' => 1,
                'currency' => 'RUB',
                'total_quantity' => 4,
                'total_amount' => '11350.00',
                'reference_type' => NULL,
                'reference_id' => NULL,
                'finalized_at' => '2024-02-13 18:50:09',
                'created_at' => '2024-02-12 14:26:11',
                'updated_at' => '2024-02-13 18:50:09',
                'deleted_at' => NULL,
                'comment' => NULL,
            ),
            
            array (
                'id' => 104,
                'provider_id' => 2,
                'barcode' => '2024 02 13 000002',
                'user_id' => 1,
                'warehouse_id' => 1,
                'currency' => 'RUB',
                'total_quantity' => 1,
                'total_amount' => '0.00',
                'reference_type' => 'client_order',
                'reference_id' => 89,
                'finalized_at' => '2024-02-13 13:31:08',
                'created_at' => '2024-02-13 13:30:48',
                'updated_at' => '2024-02-13 13:31:08',
                'deleted_at' => NULL,
                'comment' => NULL,
            ),
            
            array (
                'id' => 105,
                'provider_id' => 5,
                'barcode' => '2024 02 13 000005',
                'user_id' => 1,
                'warehouse_id' => 1,
                'currency' => 'RUB',
                'total_quantity' => 1,
                'total_amount' => '0.00',
                'reference_type' => 'client_order',
                'reference_id' => 90,
                'finalized_at' => '2024-02-13 13:39:55',
                'created_at' => '2024-02-13 13:39:38',
                'updated_at' => '2024-02-13 13:39:55',
                'deleted_at' => NULL,
                'comment' => NULL,
            ),
            
            array (
                'id' => 106,
                'provider_id' => 2,
                'barcode' => '2024 02 14 000002',
                'user_id' => 1,
                'warehouse_id' => 1,
                'currency' => 'RUB',
                'total_quantity' => 1,
                'total_amount' => '0.00',
                'reference_type' => 'client_order',
                'reference_id' => 91,
                'finalized_at' => '2024-02-14 07:31:00',
                'created_at' => '2024-02-14 07:27:01',
                'updated_at' => '2024-02-14 07:31:00',
                'deleted_at' => NULL,
                'comment' => NULL,
            ),
            
            array (
                'id' => 107,
                'provider_id' => 2,
                'barcode' => '2024 02 14 000002',
                'user_id' => 1,
                'warehouse_id' => 1,
                'currency' => 'RUB',
                'total_quantity' => 3,
                'total_amount' => '4250.00',
                'reference_type' => 'client_order',
                'reference_id' => 92,
                'finalized_at' => '2024-02-14 14:04:13',
                'created_at' => '2024-02-14 14:03:53',
                'updated_at' => '2024-02-14 14:04:13',
                'deleted_at' => NULL,
                'comment' => NULL,
            ),
            
            array (
                'id' => 109,
                'provider_id' => 2,
                'barcode' => '2024 02 18 000002',
                'user_id' => 1,
                'warehouse_id' => 1,
                'currency' => 'RUB',
                'total_quantity' => 1,
                'total_amount' => '0.00',
                'reference_type' => NULL,
                'reference_id' => NULL,
                'finalized_at' => '2024-02-18 13:38:45',
                'created_at' => '2024-02-18 13:22:47',
                'updated_at' => '2024-02-18 13:38:45',
                'deleted_at' => NULL,
                'comment' => NULL,
            ),
            
            array (
                'id' => 110,
                'provider_id' => 2,
                'barcode' => '2024 02 18 000002',
                'user_id' => 1,
                'warehouse_id' => 1,
                'currency' => 'RUB',
                'total_quantity' => 6,
                'total_amount' => '0.00',
                'reference_type' => NULL,
                'reference_id' => NULL,
                'finalized_at' => '2024-02-20 20:11:40',
                'created_at' => '2024-02-18 13:39:26',
                'updated_at' => '2024-02-20 20:11:40',
                'deleted_at' => NULL,
                'comment' => NULL,
            ),
            
            array (
                'id' => 111,
                'provider_id' => 2,
                'barcode' => '2024 02 23 000002',
                'user_id' => 1,
                'warehouse_id' => 1,
                'currency' => 'RUB',
                'total_quantity' => 6,
                'total_amount' => '146.00',
                'reference_type' => 'client_order',
                'reference_id' => 94,
                'finalized_at' => '2024-02-23 17:12:30',
                'created_at' => '2024-02-23 17:12:11',
                'updated_at' => '2024-02-23 17:12:30',
                'deleted_at' => NULL,
                'comment' => NULL,
            ),
            
            array (
                'id' => 112,
                'provider_id' => 2,
                'barcode' => '2024 02 25 000002',
                'user_id' => 1,
                'warehouse_id' => 1,
                'currency' => 'RUB',
                'total_quantity' => 2,
                'total_amount' => '892.00',
                'reference_type' => NULL,
                'reference_id' => NULL,
                'finalized_at' => '2024-02-25 09:56:54',
                'created_at' => '2024-02-25 09:56:01',
                'updated_at' => '2024-02-25 09:56:54',
                'deleted_at' => NULL,
                'comment' => NULL,
            ),
            
            array (
                'id' => 113,
                'provider_id' => 2,
                'barcode' => '2024 02 25 000002',
                'user_id' => 1,
                'warehouse_id' => 1,
                'currency' => 'RUB',
                'total_quantity' => 1,
                'total_amount' => '1000.00',
                'reference_type' => NULL,
                'reference_id' => NULL,
                'finalized_at' => '2024-02-27 14:25:55',
                'created_at' => '2024-02-25 09:57:54',
                'updated_at' => '2024-02-27 14:25:55',
                'deleted_at' => NULL,
                'comment' => NULL,
            ),
            
            array (
                'id' => 114,
                'provider_id' => 2,
                'barcode' => '2024 02 27 000002',
                'user_id' => 1,
                'warehouse_id' => 1,
                'currency' => 'RUB',
                'total_quantity' => 10,
                'total_amount' => '1923.00',
                'reference_type' => 'client_order',
                'reference_id' => 95,
                'finalized_at' => '2024-02-27 12:21:56',
                'created_at' => '2024-02-27 11:03:18',
                'updated_at' => '2024-02-27 12:21:56',
                'deleted_at' => NULL,
                'comment' => NULL,
            ),
            
            array (
                'id' => 115,
                'provider_id' => 8,
                'barcode' => '2024 02 27 000008',
                'user_id' => 1,
                'warehouse_id' => 1,
                'currency' => 'RUB',
                'total_quantity' => 4,
                'total_amount' => '11600.00',
                'reference_type' => 'client_order',
                'reference_id' => 97,
                'finalized_at' => '2024-02-27 12:33:27',
                'created_at' => '2024-02-27 12:23:08',
                'updated_at' => '2024-02-27 12:33:27',
                'deleted_at' => NULL,
                'comment' => NULL,
            ),
            
            array (
                'id' => 116,
                'provider_id' => 1,
                'barcode' => '2024 02 27 000001',
                'user_id' => 1,
                'warehouse_id' => 1,
                'currency' => 'RUB',
                'total_quantity' => 7,
                'total_amount' => '270.00',
                'reference_type' => 'client_order',
                'reference_id' => 99,
                'finalized_at' => '2024-02-27 13:38:12',
                'created_at' => '2024-02-27 13:37:55',
                'updated_at' => '2024-02-27 13:38:12',
                'deleted_at' => NULL,
                'comment' => NULL,
            ),
            
            array (
                'id' => 120,
                'provider_id' => 2,
                'barcode' => '2024 02 28 000002',
                'user_id' => 1,
                'warehouse_id' => 1,
                'currency' => 'RUB',
                'total_quantity' => 4,
                'total_amount' => '0.00',
                'reference_type' => 'client_order',
                'reference_id' => 101,
                'finalized_at' => '2024-02-28 15:57:10',
                'created_at' => '2024-02-28 15:56:43',
                'updated_at' => '2024-02-28 15:57:10',
                'deleted_at' => NULL,
                'comment' => NULL,
            ),
            
            array (
                'id' => 121,
                'provider_id' => 2,
                'barcode' => '2024 03 01 000002',
                'user_id' => 1,
                'warehouse_id' => 1,
                'currency' => 'RUB',
                'total_quantity' => 4,
                'total_amount' => '0.00',
                'reference_type' => 'client_order',
                'reference_id' => 102,
                'finalized_at' => '2024-03-01 08:06:08',
                'created_at' => '2024-03-01 08:05:48',
                'updated_at' => '2024-03-01 08:06:08',
                'deleted_at' => NULL,
                'comment' => NULL,
            ),
            
            array (
                'id' => 122,
                'provider_id' => 2,
                'barcode' => '2024 03 03 000002',
                'user_id' => 1,
                'warehouse_id' => 1,
                'currency' => 'RUB',
                'total_quantity' => 11,
                'total_amount' => '4337.00',
                'reference_type' => 'client_order',
                'reference_id' => 103,
                'finalized_at' => '2024-03-03 14:31:33',
                'created_at' => '2024-03-03 14:31:04',
                'updated_at' => '2024-03-03 14:31:33',
                'deleted_at' => NULL,
                'comment' => NULL,
            ),
            
            array (
                'id' => 123,
                'provider_id' => 2,
                'barcode' => '2024 03 04 000002',
                'user_id' => 1,
                'warehouse_id' => 1,
                'currency' => 'RUB',
                'total_quantity' => 1,
                'total_amount' => '0.00',
                'reference_type' => 'client_order',
                'reference_id' => 104,
                'finalized_at' => '2024-03-04 08:51:21',
                'created_at' => '2024-03-04 08:51:03',
                'updated_at' => '2024-03-04 08:51:21',
                'deleted_at' => NULL,
                'comment' => NULL,
            ),
            
            array (
                'id' => 124,
                'provider_id' => 2,
                'barcode' => '2024 03 10 000002',
                'user_id' => 1,
                'warehouse_id' => 1,
                'currency' => 'RUB',
                'total_quantity' => 2,
                'total_amount' => '0.00',
                'reference_type' => 'client_order',
                'reference_id' => 105,
                'finalized_at' => '2024-03-10 06:56:36',
                'created_at' => '2024-03-10 06:56:13',
                'updated_at' => '2024-03-10 06:56:36',
                'deleted_at' => NULL,
                'comment' => NULL,
            ),
            
            array (
                'id' => 125,
                'provider_id' => 5,
                'barcode' => '2024 03 19 000005',
                'user_id' => 1,
                'warehouse_id' => 1,
                'currency' => 'RUB',
                'total_quantity' => 2,
                'total_amount' => '6400.00',
                'reference_type' => 'client_order',
                'reference_id' => 106,
                'finalized_at' => '2024-03-19 09:01:30',
                'created_at' => '2024-03-19 09:01:01',
                'updated_at' => '2024-03-19 09:01:30',
                'deleted_at' => NULL,
                'comment' => NULL,
            ),
            
            array (
                'id' => 126,
                'provider_id' => 2,
                'barcode' => '2024 03 26 000002',
                'user_id' => 1,
                'warehouse_id' => 1,
                'currency' => 'RUB',
                'total_quantity' => 6,
                'total_amount' => '0.00',
                'reference_type' => 'client_order',
                'reference_id' => 108,
                'finalized_at' => '2024-03-26 09:17:09',
                'created_at' => '2024-03-26 09:16:49',
                'updated_at' => '2024-03-26 09:17:09',
                'deleted_at' => NULL,
                'comment' => NULL,
            ),
            
            array (
                'id' => 127,
                'provider_id' => 2,
                'barcode' => '2024 04 08 1712534400 000002',
                'user_id' => 1,
                'warehouse_id' => 1,
                'currency' => 'RUB',
                'total_quantity' => 15,
                'total_amount' => '0.00',
                'reference_type' => 'client_order',
                'reference_id' => 109,
                'finalized_at' => '2024-04-08 14:30:55',
                'created_at' => '2024-04-08 14:30:32',
                'updated_at' => '2024-04-08 14:30:55',
                'deleted_at' => NULL,
                'comment' => NULL,
            ),
            
            array (
                'id' => 128,
                'provider_id' => 2,
                'barcode' => '2024 04 08 1712534400 000002',
                'user_id' => 1,
                'warehouse_id' => 1,
                'currency' => 'RUB',
                'total_quantity' => 2,
                'total_amount' => '0.00',
                'reference_type' => 'client_order',
                'reference_id' => 110,
                'finalized_at' => '2024-04-08 14:35:30',
                'created_at' => '2024-04-08 14:35:07',
                'updated_at' => '2024-04-08 14:35:30',
                'deleted_at' => NULL,
                'comment' => NULL,
            ),
            
            array (
                'id' => 129,
                'provider_id' => 2,
                'barcode' => '2024 04 10 1712707200 000002',
                'user_id' => 1,
                'warehouse_id' => 1,
                'currency' => 'RUB',
                'total_quantity' => 5,
                'total_amount' => '1339.00',
                'reference_type' => 'client_order',
                'reference_id' => 112,
                'finalized_at' => '2024-04-10 10:10:26',
                'created_at' => '2024-04-10 10:10:08',
                'updated_at' => '2024-04-10 10:10:26',
                'deleted_at' => NULL,
                'comment' => NULL,
            ),
            
            array (
                'id' => 130,
                'provider_id' => 2,
                'barcode' => '2024 05 03 1714694400 000002',
                'user_id' => 1,
                'warehouse_id' => 1,
                'currency' => 'RUB',
                'total_quantity' => 1,
                'total_amount' => '800.00',
                'reference_type' => 'client_order',
                'reference_id' => 113,
                'finalized_at' => '2024-05-03 12:12:33',
                'created_at' => '2024-05-03 12:12:02',
                'updated_at' => '2024-05-03 12:12:33',
                'deleted_at' => NULL,
                'comment' => NULL,
            ),
        ));
        
        
    }
}